import { Product, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Магнітні наліпки на авто',
    slug: 'magnitni-nalipki-na-avto',
    image: 'https://images.prom.ua/4296986097_w297_h200_magnitni-nalipki-na.jpg',
    description: 'Міцні вінілові магніти на авто із захисною ламінацією від непогоди та УФ.',
    isFeatured: true,
  },
  {
    id: 'cat-2',
    name: 'Магніти ЗСУ та Військова Символіка',
    slug: 'magniti-zsu',
    image: 'https://images.prom.ua/6955960434_w297_h200_magniti-zsu.jpg',
    description: 'Символіка бригад ЗСУ, Морська піхота, Вовки Да Вінчі, Тризуб.',
    isFeatured: true,
  },
  {
    id: 'cat-3',
    name: 'Попереджувальні знаки ⚠️ Міни / Охорона',
    slug: 'poperedzhuvalni-znaki',
    image: 'https://images.prom.ua/6964429952_w297_h200_poperedzhuvalni-znaki-.jpg',
    description: 'Знакибезпеки "ОБЕРЕЖНО МІНИ!", "ОХОРОНА", "НАВЧАЛЬНИЙ".',
    isFeatured: true,
  },
  {
    id: 'cat-4',
    name: 'Таблички адресні та інформаційні',
    slug: 'tablichki-adresni',
    image: 'https://images.prom.ua/3984689222_w297_h200_tablichki-adresni.jpg',
    description: 'Фасадні та адресні таблички з назвою вулиці та номером будинку.',
    isFeatured: true,
  },
  {
    id: 'cat-5',
    name: 'Сувенірні та транзитні автономери',
    slug: 'suvenirni-avtonomera',
    image: 'https://images.prom.ua/6871345002_w500_h500_suvenirnij-nomer-eurocar.jpg',
    description: 'Автономери з позывним, логотипом, ДШВ, пластикові та алюмінієві.',
    isFeatured: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p2851787526',
    name: 'Магнітні візитки для майстрів: сантехнік | електрик | опалення | ремонт',
    slug: 'magnitni-vizitki-dlya-majstriv',
    price: 20,
    oldPrice: 25,
    sku: 'VIZ-01',
    status: 'Під замовлення',
    categoryId: 'cat-1',
    description: 'Якісні вінілові магнітні візитки для майстрів ремонту, сантехніків, електриків.',
    image: 'https://images.prom.ua/6972629971_w500_h500_magnitni-vizitki-dlya.jpg',
    images: JSON.stringify(['https://images.prom.ua/6972629971_w500_h500_magnitni-vizitki-dlya.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2845969109',
    name: 'Магнітний рекламний постер — Вугілля / Дрова / Брикети',
    slug: 'magnitnij-reklamnij-poster-vugillya-drova',
    price: 100,
    oldPrice: 120,
    sku: 'POSTER-01',
    status: 'Під замовлення',
    categoryId: 'cat-1',
    description: 'Рекламний магнітний постер на авто для доставки дров, вугілля та брикетів.',
    image: 'https://images.prom.ua/6964220216_w500_h500_magnitnij-reklamnij-poster.jpg',
    images: JSON.stringify(['https://images.prom.ua/6964220216_w500_h500_magnitnij-reklamnij-poster.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2846338378',
    name: 'Магніти для Служб Охорони',
    slug: 'magniti-dlya-sluzhb-ohoroni',
    price: 100,
    oldPrice: 130,
    sku: 'SEC-100',
    status: 'В наявності',
    categoryId: 'cat-3',
    description: 'Магнітні наліпки для автомобілів служб охорони. Яскраві та стійкі.',
    image: 'https://images.prom.ua/6964688153_w500_h500_magniti-dlya-sluzhb.jpg',
    images: JSON.stringify(['https://images.prom.ua/6964688153_w500_h500_magniti-dlya-sluzhb.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2846576177',
    name: 'Смішний магніт на авто “ГороПчик, а шо ти робиш?” | Мем',
    slug: 'smishnij-magnit-na-avto-goropchik',
    price: 100,
    oldPrice: 120,
    sku: 'MEM-01',
    status: 'Під замовлення',
    categoryId: 'cat-1',
    description: 'Гумористична магнітна наклейка на автомобіль. Вологостійкий уф-друк.',
    image: 'https://images.prom.ua/6971735141_w500_h500_smishnij-magnit-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6971735141_w500_h500_smishnij-magnit-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2853083971',
    name: 'Патріотичний магніт на авто Тризуб | Магнітні наклейки ЗСУ',
    slug: 'patriotichnij-magnit-na-avto-trizub',
    price: 100,
    oldPrice: 125,
    sku: 'ZSU-TRIZUB',
    status: 'Під замовлення',
    categoryId: 'cat-2',
    description: 'Патріотичний магніт на авто Герб України Тризуб. Різні варіанти дизайну.',
    image: 'https://images.prom.ua/6974843980_w500_h500_patriotichnij-magnit-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6974843980_w500_h500_patriotichnij-magnit-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2717952132',
    name: 'Наклейка ЗСУ квадрат синьо-жовтий 30*30см',
    slug: 'naklejka-zsu-kvadrat-30x30',
    price: 125,
    oldPrice: 150,
    sku: 'квадрат',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітна наклейка ЗСУ квадратна синьо-жовта 30х30 см.',
    image: 'https://images.prom.ua/6794611879_w500_h500_naklejka-zsu-kvadrat.jpg',
    images: JSON.stringify(['https://images.prom.ua/6794611879_w500_h500_naklejka-zsu-kvadrat.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2735821997',
    name: 'Наклейка магнітна на авто Колона 15*15см',
    slug: 'naklejka-magnitna-kolona-15x15',
    price: 130,
    oldPrice: 160,
    sku: 'колона',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Магнітний знак "Колона" 15х15 см для позначення автомобілів у колоні.',
    image: 'https://images.prom.ua/6809609685_w500_h500_naklejka-magnitna-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6809609685_w500_h500_naklejka-magnitna-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2716395430',
    name: 'Наклейка магнітна Каблук 15*15см',
    slug: 'naklejka-magnitna-kabluk-15x15',
    price: 150,
    oldPrice: 180,
    sku: 'каблук',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Попереджувальний магнітний знак "Каблук" 15х15 см.',
    image: 'https://images.prom.ua/6793705342_w500_h500_naklejka-magnitna-kabluk.jpg',
    images: JSON.stringify(['https://images.prom.ua/6793705342_w500_h500_naklejka-magnitna-kabluk.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2716465738',
    name: 'Наклейка квадрат ЗСУ стрілка 40*40см',
    slug: 'naklejka-kvadrat-zsu-strelka-40x40',
    price: 150,
    oldPrice: 180,
    sku: 'наклейка',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Тактична наклейка ЗСУ квадратна зі стрілкою 40х40 см.',
    image: 'https://images.prom.ua/6793762684_w500_h500_naklejka-kvadrat-zsu.jpg',
    images: JSON.stringify(['https://images.prom.ua/6793762684_w500_h500_naklejka-kvadrat-zsu.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2717729965',
    name: 'Наклейка магнітна Вовки Да Вінчі 15*15см',
    slug: 'naklejka-magnitna-vovki-da-vinchi-15x15',
    price: 150,
    oldPrice: 180,
    sku: 'да вінчі',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітна наклейка з символікою спецпідрозділу "Вовки Да Вінчі" 15х15 см.',
    image: 'https://images.prom.ua/6794528403_w500_h500_naklejka-magnitna-vovki.jpg',
    images: JSON.stringify(['https://images.prom.ua/6794528403_w500_h500_naklejka-magnitna-vovki.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2845101710',
    name: 'Магніт на авто Герб Микуличин | Виготовлення гербів під замовлення',
    slug: 'magnit-na-avto-gerb-mikulichin',
    price: 150,
    oldPrice: 180,
    sku: 'GERB-MIK',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Магнітний герб міста Микуличин. Виготовлення гербів міст та ОТГ.',
    image: 'https://images.prom.ua/6963042275_w500_h500_magnit-na-avto.jpg',
    images: JSON.stringify(['https://images.prom.ua/6963042275_w500_h500_magnit-na-avto.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2718682424',
    name: 'Табличка з пластику Паркування заборонено 30*20см',
    slug: 'tablichka-z-plastiku-parkuvannya-zaboroneno',
    price: 180,
    oldPrice: 210,
    sku: 'паркування',
    status: 'В наявності',
    categoryId: 'cat-3',
    description: 'Пластикова попереджувальна табличка "Паркування заборонено" 30х20 см.',
    image: 'https://images.prom.ua/6795155337_w500_h500_tablichka-z-plastiku.jpg',
    images: JSON.stringify(['https://images.prom.ua/6795155337_w500_h500_tablichka-z-plastiku.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2843193642',
    name: 'Магніт на авто Єгерська служба | Щит з гербом України 20х15см',
    slug: 'magnit-na-avto-egerska-sluzhba',
    price: 180,
    oldPrice: 220,
    sku: 'ег',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Магнітна наклейка "Єгерська служба / Мисливці" 20х15 см.',
    image: 'https://images.prom.ua/6960970817_w500_h500_magnit-na-avto.jpg',
    images: JSON.stringify(['https://images.prom.ua/6960970817_w500_h500_magnit-na-avto.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2713534620',
    name: 'Сувенірні автономера з позивним',
    slug: 'suvenirni-avtonomera-z-pozivnim',
    price: 200,
    oldPrice: 250,
    sku: 'позивний',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Індивідуальне виготовлення автономерів з позивним військових або іменем.',
    image: 'https://images.prom.ua/6960951508_w500_h500_suvenirni-avtonomera-z.jpg',
    images: JSON.stringify(['https://images.prom.ua/6960951508_w500_h500_suvenirni-avtonomera-z.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2717507021',
    name: 'Транзитні автономера пластикові',
    slug: 'tranzitni-avtonomera-plastikovi',
    price: 200,
    oldPrice: 240,
    sku: 'транзитні',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Пластково-композитні транзитні номери на авто стандартного розміру.',
    image: 'https://images.prom.ua/6794393214_w500_h500_tranzitni-avtonomera-plastikovi.jpg',
    images: JSON.stringify(['https://images.prom.ua/6794393214_w500_h500_tranzitni-avtonomera-plastikovi.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2762673304',
    name: 'Магнітна наклейка на авто 1 ОШП «Да Вінчі» 25*20см',
    slug: 'magnitna-naklejka-на-avto-1-oshp-da-vinchi',
    price: 200,
    oldPrice: 240,
    sku: '1ошп',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітний банер на авто 1 окремого штурмового полку Да Вінчі 25х20 см.',
    image: 'https://images.prom.ua/6841302692_w500_h500_magnitna-naklejka-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6841302692_w500_h500_magnitna-naklejka-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2764392664',
    name: 'Волонтер магнітна наліпка на авто',
    slug: 'volonter-magnitna-nalipka-na-avto',
    price: 200,
    oldPrice: 250,
    sku: 'волонтер',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Розпізнавальний волонтерський магніт на автомобіль для волонтерських місій.',
    image: 'https://images.prom.ua/6844236685_w500_h500_volonter-magnitna-nalipka.jpg',
    images: JSON.stringify(['https://images.prom.ua/6844236685_w500_h500_volonter-magnitna-nalipka.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2784266269',
    name: 'Сувенірний номер EUROCAR CARZONE 519х112 мм',
    slug: 'suvenirnij-nomer-eurocar-carzone',
    price: 200,
    oldPrice: 240,
    sku: 'EUROCAR',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Сувенірний автономер EUROCAR з УФ-друком на алюмінієвому композиті.',
    image: 'https://images.prom.ua/6871345002_w500_h500_suvenirnij-nomer-eurocar.jpg',
    images: JSON.stringify(['https://images.prom.ua/6871345002_w500_h500_suvenirnij-nomer-eurocar.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2785004530',
    name: 'Сувенірний номер (ДШВ ЗСУ) 519х112 мм',
    slug: 'suvenirnij-nomer-dshv-zsu',
    price: 200,
    oldPrice: 250,
    sku: 'ДШВ',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Сувенірний військовий номер ДШВ ЗСУ з символікою десантно-штурмових військ.',
    image: 'https://images.prom.ua/6872756468_w500_h500_suvenirnij-nomer-dshv.jpg',
    images: JSON.stringify(['https://images.prom.ua/6872756468_w500_h500_suvenirnij-nomer-dshv.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2858010933',
    name: 'Сувенірний номер на авто «МЕХАНІК» | 52х11 см',
    slug: 'suvenirnij-nomer-avto-mehanik',
    price: 200,
    oldPrice: 250,
    sku: 'МЕХАНІК',
    status: 'Під замовлення',
    categoryId: 'cat-5',
    description: 'Патріотична авто табличка "МЕХАНІК" з УФ-друком на міцному пластику.',
    image: 'https://images.prom.ua/6983588355_w500_h500_suvenirnij-nomer-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6983588355_w500_h500_suvenirnij-nomer-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2764161335',
    name: 'Магнітна наклейка на авто ЗСУ 25*25см',
    slug: 'magnitna-naklejka-на-avto-zsu-25x25',
    price: 220,
    oldPrice: 260,
    sku: 'ЗСУ 25',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Офіційна розпізнавальна магнітна наклейка ЗСУ розміром 25х25 см.',
    image: 'https://images.prom.ua/6843747891_w500_h500_magnitna-naklejka-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6843747891_w500_h500_magnitna-naklejka-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2735613139',
    name: 'Авто номер військовий з алюмінію композиту',
    slug: 'avto-nomer-vijskovij-z-kompozitu',
    price: 230,
    oldPrice: 270,
    sku: 'композит',
    status: 'Під замовлення',
    categoryId: 'cat-5',
    description: 'Військовий автономер з алюмінієвого композитного матеріалу 3 мм.',
    image: 'https://images.prom.ua/6809283765_w500_h500_avto-nomer-vijskovij.jpg',
    images: JSON.stringify(['https://images.prom.ua/6809283765_w500_h500_avto-nomer-vijskovij.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2854299656',
    name: 'Світловідбиваючий магніт на авто “К” | Reflective Edition 15х15 см',
    slug: 'svitlovidbivayuchij-magnit-k-15x15',
    price: 230,
    oldPrice: 280,
    sku: 'REF-K',
    status: 'В наявності',
    categoryId: 'cat-3',
    description: 'Світловідбиваючий магнітний знак "Каблук" / "К" підвищеної видимості вночі.',
    image: 'https://images.prom.ua/6976967220_w500_h500_svitlovidbivayuchij-magnit-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6976967220_w500_h500_svitlovidbivayuchij-magnit-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2767106194',
    name: 'Холодний яр 93 бригада магнітна наклейка на авто 30*25см',
    slug: 'holodnij-yar-93-brigada-magnitna-naklejka-30x25',
    price: 240,
    oldPrice: 290,
    sku: '93 омбр',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітна наклейка 93 окремої механізованої бригади "Холодний Яр" 30х25 см.',
    image: 'https://images.prom.ua/6848857086_w500_h500_holodnij-yar-93.jpg',
    images: JSON.stringify(['https://images.prom.ua/6848857086_w500_h500_holodnij-yar-93.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2716279483',
    name: 'Магнітна наклейка Морська піхота 25*25см',
    slug: 'magnitna-naklejka-morska-pihota-25x25',
    price: 250,
    oldPrice: 300,
    sku: 'морська піхота',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Якісна магнітна наклейка "Морська піхота" 25х25 см з УФ-ламінацією.',
    image: 'https://images.prom.ua/6793582624_w500_h500_magnitna-naklejka-morska.jpg',
    images: JSON.stringify(['https://images.prom.ua/6793582624_w500_h500_magnitna-naklejka-morska.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2851307059',
    name: 'Магніт “НАВЧАЛЬНИЙ” на авто | Знак Учбовий автомобіль',
    slug: 'magnit-navchalnij-na-avto',
    price: 250,
    oldPrice: 300,
    sku: 'НАВЧАЛЬНИЙ',
    status: 'В наявності',
    categoryId: 'cat-3',
    description: 'Знімний магнітний знак "НАВЧАЛЬНИЙ" / "У" для автошкол та учнів за кермом.',
    image: 'https://images.prom.ua/6971790306_w500_h500_magnit-navchalnij-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6971790306_w500_h500_magnit-navchalnij-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
];
