import { Product, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Магнітні наліпки на авто',
    slug: 'magnitni-nalipki-na-avto',
    image: 'https://images.prom.ua/4296986097_w297_h200_magnitni-nalipki-na.jpg',
    description: 'Міцні вінілові магніти на авто із захисною ламінацією від непогоди та УФ.',
    isFeatured: true,
  },
  {
    id: 'cat-2',
    name: 'Магніти ЗСУ та Військова Символіка',
    slug: 'magniti-zsu',
    image: 'https://images.prom.ua/6955960434_w297_h200_magniti-zsu.jpg',
    description: 'Символіка бригад ЗСУ, Морська піхота, Вовки Да Вінчі, Тризуб, Розпізнавальні знаки.',
    isFeatured: true,
  },
  {
    id: 'cat-3',
    name: 'Попереджувальні знаки ⚠️ Міни / Охорона',
    slug: 'poperedzhuvalni-znaki',
    image: 'https://images.prom.ua/6964429952_w297_h200_poperedzhuvalni-znaki-.jpg',
    description: 'Знаки безпеки "ОБЕРЕЖНО МІНИ!", "ОХОРОНА", "НАВЧАЛЬНИЙ", "КОЛОНА".',
    isFeatured: true,
  },
  {
    id: 'cat-4',
    name: 'Таблички адресні та інформаційні',
    slug: 'tablichki-adresni',
    image: 'https://images.prom.ua/3984689222_w297_h200_tablichki-adresni.jpg',
    description: 'Фасадні та адресні таблички, паркування заборонено, ритуальні металеві таблички.',
    isFeatured: true,
  },
  {
    id: 'cat-5',
    name: 'Сувенірні та транзитні автономери',
    slug: 'suvenirni-avtonomera',
    image: 'https://images.prom.ua/6871345002_w500_h500_suvenirnij-nomer-eurocar.jpg',
    description: 'Автономери з позивним, логотипом, ДШВ, пластикові та алюмінієві композитні.',
    isFeatured: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Page 1 & 2 items
  {
    id: 'p2851787526',
    name: 'Магнітні візитки для майстрів: сантехнік | електрик | опалення | ремонт',
    slug: 'magnitni-vizitki-dlya-majstriv',
    price: 20,
    oldPrice: 25,
    sku: 'VIZ-01',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Якісні вінілові магнітні візитки для майстрів ремонту, сантехніків, електриків.',
    image: 'https://images.prom.ua/6972629971_w500_h500_magnitni-vizitki-dlya.jpg',
    images: JSON.stringify(['https://images.prom.ua/6972629971_w500_h500_magnitni-vizitki-dlya.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2855571903',
    name: 'Магнітний хрест ЗСУ 15×15 см на авто | Білий або Чорний',
    slug: 'magnitnij-hrest-zsu-15x15',
    price: 98,
    oldPrice: 120,
    sku: 'KREST-15',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітний тактичний хрест ЗСУ 15х15 см для маркування легкових авто та техніки.',
    image: 'https://images.prom.ua/6979516750_w500_h500_magnitnij-hrest-zsu.jpg',
    images: JSON.stringify(['https://images.prom.ua/6979516750_w500_h500_magnitnij-hrest-zsu.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2845969109',
    name: 'Магнітний рекламний постер — Вугілля / Дрова / Брикети',
    slug: 'magnitnij-reklamnij-poster-vugillya-drova',
    price: 100,
    oldPrice: 120,
    sku: 'POSTER-01',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Рекламний магнітний постер на авто для доставки дров, вугілля та брикетів.',
    image: 'https://images.prom.ua/6964220216_w500_h500_magnitnij-reklamnij-poster.jpg',
    images: JSON.stringify(['https://images.prom.ua/6964220216_w500_h500_magnitnij-reklamnij-poster.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2846338378',
    name: 'Магніти для Служб Охорони',
    slug: 'magnity-dlya-sluzhb-ohrany',
    price: 100,
    oldPrice: 130,
    sku: 'OHR-01',
    status: 'В наявності',
    categoryId: 'cat-3',
    description: 'Спеціальні магнітні знаки для служб безпеки, патрульних авто та інкасації.',
    image: 'https://images.prom.ua/6964688153_w500_h500_magniti-dlya-sluzhb.jpg',
    images: JSON.stringify(['https://images.prom.ua/6964688153_w500_h500_magniti-dlya-sluzhb.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2846576177',
    name: 'Смішний магніт на авто “ГороПчик, а шо ти робиш?” | Український гумор мем',
    slug: 'smishnij-magnit-na-avto-goropchik',
    price: 100,
    oldPrice: 120,
    sku: 'MEM-01',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Популярний мем-магніт на авто ГороПчик. Яскравий УФ-друк, стійкий до мийки.',
    image: 'https://images.prom.ua/6971735141_w500_h500_smishnij-magnit-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6971735141_w500_h500_smishnij-magnit-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2853083971',
    name: 'Патріотичний магніт на авто Тризуб | Магнітні наклейки ЗСУ',
    slug: 'patriotichnij-magnit-na-avto-trizub',
    price: 100,
    oldPrice: 130,
    sku: 'TRZ-100',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітна наклейка Герб України Тризуб для авто та техніки.',
    image: 'https://images.prom.ua/6974843980_w500_h500_patriotichnij-magnit-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6974843980_w500_h500_patriotichnij-magnit-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2717952132',
    name: 'Наклейка ЗСУ квадрат синьо-жовтий 30*30см',
    slug: 'naklejka-zsu-kvadrat-30x30',
    price: 125,
    oldPrice: 150,
    sku: 'ZSU-3030',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Офіційний розпізнавальний квадратний магнітний знак ЗСУ 30х30 см.',
    image: 'https://images.prom.ua/6794611879_w500_h500_naklejka-zsu-kvadrat.jpg',
    images: JSON.stringify(['https://images.prom.ua/6794611879_w500_h500_naklejka-zsu-kvadrat.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2735821997',
    name: 'Наклейка магнітна на авто Колона 15*15см',
    slug: 'naklejka-magnitna-na-avto-kolona-15x15',
    price: 130,
    oldPrice: 150,
    sku: 'KOLONA-15',
    status: 'В наявності',
    categoryId: 'cat-3',
    description: 'Попереджувальний магнітний знак "КОЛОНА" для транспорту військових колони.',
    image: 'https://images.prom.ua/6809609685_w500_h500_naklejka-magnitna-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6809609685_w500_h500_naklejka-magnitna-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2716395430',
    name: 'Наклейка магнітна Каблук 15*15см',
    slug: 'naklejka-magnitna-kabluk-15x15',
    price: 150,
    oldPrice: 180,
    sku: 'KABLUK-15',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Попереджувальний магніт на авто "Каблук". Захисна ламінація.',
    image: 'https://images.prom.ua/6793705342_w500_h500_naklejka-magnitna-kabluk.jpg',
    images: JSON.stringify(['https://images.prom.ua/6793705342_w500_h500_naklejka-magnitna-kabluk.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2716465738',
    name: 'Наклейка квадрат ЗСУ стрілка 40*40см',
    slug: 'naklejka-kvadrat-zsu-strilka-40x40',
    price: 150,
    oldPrice: 180,
    sku: 'ZSU-STR-40',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Великий магніт ЗСУ стрілка 40х40 см для маркування техніки.',
    image: 'https://images.prom.ua/6793762684_w500_h500_naklejka-kvadrat-zsu.jpg',
    images: JSON.stringify(['https://images.prom.ua/6793762684_w500_h500_naklejka-kvadrat-zsu.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2717729965',
    name: 'Наклейка магнітна Вовки Да Вінчі 15*15см',
    slug: 'naklejka-magnitna-vovki-da-vinchi-15x15',
    price: 150,
    oldPrice: 180,
    sku: 'VDV-15',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітна наклейка Вовки Да Вінчі. Посилена ламінація.',
    image: 'https://images.prom.ua/6794528403_w500_h500_naklejka-magnitna-vovki.jpg',
    images: JSON.stringify(['https://images.prom.ua/6794528403_w500_h500_naklejka-magnitna-vovki.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2845101710',
    name: 'Магніт на авто Герб Микуличин | Магнітний герб міста',
    slug: 'magnit-na-avto-gerb-mikulichin',
    price: 150,
    oldPrice: 180,
    sku: 'GERB-MIK',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Магнітний герб села Микуличин на автотранспорт.',
    image: 'https://images.prom.ua/6963042275_w500_h500_magnit-na-avto.jpg',
    images: JSON.stringify(['https://images.prom.ua/6963042275_w500_h500_magnit-na-avto.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2718682424',
    name: 'Табличка з пластику Паркування заборонено 30*20см',
    slug: 'tablichka-z-plastiku-parkuvannya-zaboroneno-30x20',
    price: 180,
    oldPrice: 220,
    sku: 'TAB-PARK',
    status: 'В наявності',
    categoryId: 'cat-4',
    description: 'Інформаційна пластикова табличка "Паркування заборонено" 30х20 см.',
    image: 'https://images.prom.ua/6795155337_w500_h500_tablichka-z-plastiku.jpg',
    images: JSON.stringify(['https://images.prom.ua/6795155337_w500_h500_tablichka-z-plastiku.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2843193642',
    name: 'Магніт на авто Єгерська служба | Щит з гербом України 20х15см',
    slug: 'magnit-na-avto-egerska-sluzhba-20x15',
    price: 180,
    oldPrice: 210,
    sku: 'EGER-2015',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Магнітна наклейка Єгерська служба УТМР для мисливців та охоронців лісу.',
    image: 'https://images.prom.ua/6960970817_w500_h500_magnit-na-avto.jpg',
    images: JSON.stringify(['https://images.prom.ua/6960970817_w500_h500_magnit-na-avto.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2713534620',
    name: 'Сувенірні автономера з позивним під замовлення',
    slug: 'suvenirni-avtonomera-z-pozivnim',
    price: 200,
    oldPrice: 240,
    sku: 'NUM-CALL',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Виготовлення імені і сувенірних автономерів з позывними ЗСУ під замовлення.',
    image: 'https://images.prom.ua/6960951508_w500_h500_suvenirni-avtonomera-z.jpg',
    images: JSON.stringify(['https://images.prom.ua/6960951508_w500_h500_suvenirni-avtonomera-z.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2717507021',
    name: 'Транзитні автономера пластикові',
    slug: 'tranzitni-avtonomera-plastikovi',
    price: 200,
    oldPrice: 230,
    sku: 'NUM-TRZ',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Пластикові транзитні автономери для автосалонів та перегону машин.',
    image: 'https://images.prom.ua/6794393214_w500_h500_tranzitni-avtonomera-plastikovi.jpg',
    images: JSON.stringify(['https://images.prom.ua/6794393214_w500_h500_tranzitni-avtonomera-plastikovi.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2762673304',
    name: 'Магнітна наклейка на авто 1 ОШП «Да Вінчі» 25*20см',
    slug: 'magnitna-naklejka-1-oshp-da-vinchi-25x20',
    price: 200,
    oldPrice: 250,
    sku: '1OSHP-2520',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Офіційна магнітна наклейка 1-го окремого штурмового полку "Да Вінчі".',
    image: 'https://images.prom.ua/6841302692_w500_h500_magnitna-naklejka-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6841302692_w500_h500_magnitna-naklejka-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2764392664',
    name: 'Волонтер магнітна наліпка на авто',
    slug: 'volonter-magnitna-nalipka-na-avto',
    price: 200,
    oldPrice: 240,
    sku: 'VOL-MAG',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітний знак "ВОЛОНТЕР" для автомобілів волонтерських місій.',
    image: 'https://images.prom.ua/6844236685_w500_h500_volonter-magnitna-nalipka.jpg',
    images: JSON.stringify(['https://images.prom.ua/6844236685_w500_h500_volonter-magnitna-nalipka.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2784266269',
    name: 'Сувенірний номер EUROCAR CARZONE — 519×112 мм УФ-друк',
    slug: 'suvenirnij-nomer-eurocar-carzone-519x112',
    price: 200,
    oldPrice: 250,
    sku: 'NUM-EUR',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Сувенірний автономер EUROCAR CARZONE з алюмінієвого композиту 519х112 мм.',
    image: 'https://images.prom.ua/6871345002_w500_h500_suvenirnij-nomer-eurocar.jpg',
    images: JSON.stringify(['https://images.prom.ua/6871345002_w500_h500_suvenirnij-nomer-eurocar.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2785004530',
    name: 'Сувенірний номер ДШВ ЗСУ | 519×112 мм Алюмінієвий композит',
    slug: 'suvenirnij-nomer-dshv-zsu-519x112',
    price: 200,
    oldPrice: 250,
    sku: 'NUM-DSHV',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Сувенірний пластиковий та композитний автономер ДШВ Десантно-штурмових військ.',
    image: 'https://images.prom.ua/6872756468_w500_h500_suvenirnij-nomer-dshv.jpg',
    images: JSON.stringify(['https://images.prom.ua/6872756468_w500_h500_suvenirnij-nomer-dshv.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2858010933',
    name: 'Сувенірний номер на авто «МЕХАНІК» | 52×11 см Патріотична табличка',
    slug: 'suvenirnij-nomer-mehanik-52x11',
    price: 200,
    oldPrice: 240,
    sku: 'NUM-MEH',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Сувенірний номерний знак МЕХАНІК з УФ-друком на пластику чи композиті.',
    image: 'https://images.prom.ua/6983588355_w500_h500_suvenirnij-nomer-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6983588355_w500_h500_suvenirnij-nomer-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2858591923',
    name: 'Сувенірні авто номери на алюмінієвому композиті для військових та позивних',
    slug: 'suvenirni-avto-nomeri-na-alyuminiyevomu-kompoziti',
    price: 200,
    oldPrice: 250,
    sku: 'NUM-COMP',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Виготовлення надміцних сувенірних номерів з алюмінієвого композиту 3 мм.',
    image: 'https://images.prom.ua/6984586040_w500_h500_suvenirni-avto-nomeri.jpg',
    images: JSON.stringify(['https://images.prom.ua/6984586040_w500_h500_suvenirni-avto-nomeri.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2764161335',
    name: 'Магнітна наклейка на авто ЗСУ 25*25см',
    slug: 'magnitna-naklejka-na-avto-zsu-25x25',
    price: 220,
    oldPrice: 260,
    sku: 'ZSU-2525',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Якісний магнітний знак ЗСУ 25х25 см для легкових авто та джипів.',
    image: 'https://images.prom.ua/6843747891_w500_h500_magnitna-naklejka-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6843747891_w500_h500_magnitna-naklejka-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },

  // Page 3 items
  {
    id: 'p2855610493',
    name: 'Магнітний розпізнавальний знак ЗСУ «Стрілки» 30х30см для авто',
    slug: 'magnitnij-rozpiznavalnij-znak-zsu-strilki-30x30',
    price: 260,
    oldPrice: 310,
    sku: 'ZSU-STR-30',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Офіційний розпізнавальний знак ЗСУ "Стрілки" на вініловому магніті.',
    image: 'https://images.prom.ua/6979540477_w500_h500_magnitnij-rozpiznavalnij-znak.jpg',
    images: JSON.stringify(['https://images.prom.ua/6979540477_w500_h500_magnitnij-rozpiznavalnij-znak.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2855621359',
    name: 'Магнітний розпізнавальний знак КРУГ 30х30см | Білий / Чорний / Оливковий',
    slug: 'magnitnij-rozpiznavalnij-znak-krug-30x30',
    price: 260,
    oldPrice: 310,
    sku: 'ZSU-KRUG-30',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Тактичний розпізнавальний магнітний круг 30х30 см у 3 кольорах.',
    image: 'https://images.prom.ua/6979546265_w500_h500_magnitnij-rozpiznavalnij-znak.jpg',
    images: JSON.stringify(['https://images.prom.ua/6979546265_w500_h500_magnitnij-rozpiznavalnij-znak.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2857819029',
    name: 'Розпізнавальний знак ЗСУ «Синій квадрат з жовтим центром» 30х30см',
    slug: 'rozpiznavalnij-znak-zsu-sinij-kvadrat-30x30',
    price: 270,
    oldPrice: 320,
    sku: 'ZSU-SIN-30',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітна наліпка для маркування техніки підрозділів ЗСУ.',
    image: 'https://images.prom.ua/6983166722_w500_h500_rozpiznavalnij-znak-zsu.jpg',
    images: JSON.stringify(['https://images.prom.ua/6983166722_w500_h500_rozpiznavalnij-znak-zsu.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },

  // Page 4 & 5 items (New complete extraction)
  {
    id: 'p2838747503',
    name: 'Магнітна наклейка на капот «Й…аний цирк» | Патріотичний гумор 30×20 / 40×30 см',
    slug: 'magnitnaya-naklejka-kapot-y-circus',
    price: 350,
    oldPrice: 400,
    sku: 'MEM-CIRCUS',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Яскравий гумористичний магніт на капот авто. Захищений УФ-ламінацією.',
    image: 'https://images.prom.ua/6955671160_w500_h500_magnitna-naklejka-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6955671160_w500_h500_magnitna-naklejka-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2838777330',
    name: 'Рекламний магніт для бізнесу «Пивна Бухта №1» — Табличка на авто / холодильник',
    slug: 'reklamnij-magnit-dlya-biznesu-pivna-buhta',
    price: 350,
    oldPrice: 400,
    sku: 'BIZ-BEER',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Рекламний вініловий магніт для просування пивних магазинів та закладів.',
    image: 'https://images.prom.ua/6955704240_w500_h500_reklamnij-magnit-dlya.jpg',
    images: JSON.stringify(['https://images.prom.ua/6955704240_w500_h500_reklamnij-magnit-dlya.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2846513929',
    name: 'Магніт на ворота “Паркування заборонено” | Попереджувальна табличка No Parking',
    slug: 'magnit-na-vorota-parkuvannya-zaboroneno',
    price: 350,
    oldPrice: 420,
    sku: 'NO-PARK-MAG',
    status: 'В наявності',
    categoryId: 'cat-4',
    description: 'Магнітна попереджувальна табличка на ворота та гараж "Паркування заборонено".',
    image: 'https://images.prom.ua/6964922718_w500_h500_magnit-na-vorota.jpg',
    images: JSON.stringify(['https://images.prom.ua/6964922718_w500_h500_magnit-na-vorota.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2851776483',
    name: 'Магніт на авто “Не бійся! Я не з ТЦК” | Військовий шеврон на машину ЗСУ',
    slug: 'magnit-avto-ne-bijsya-ya-ne-z-tczk',
    price: 350,
    oldPrice: 400,
    sku: 'NOT-TCK-PRO',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Великий патріотичний магнітний шеврон на авто "Не бійся! Я не з ТЦК".',
    image: 'https://images.prom.ua/6972615205_w500_h500_magnit-na-avto.jpg',
    images: JSON.stringify(['https://images.prom.ua/6972615205_w500_h500_magnit-na-avto.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2796670243',
    name: 'Магнітна наліпка Воїн з бородою — череп у шоломі магніти на авто',
    slug: 'magnitna-nalipka-voyin-z-borodoyu-cherep',
    price: 360,
    oldPrice: 420,
    sku: 'WARRIOR-SKULL',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Патріотичний магнітний символ "Воїн з бородою в шоломі". Захищена ламінація.',
    image: 'https://images.prom.ua/6890852146_w500_h500_magnitna-nalipka-voyin.jpg',
    images: JSON.stringify(['https://images.prom.ua/6890852146_w500_h500_magnitna-nalipka-voyin.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2836921956',
    name: 'Табличка на могилу з квітами і свічками Металева пам’ятна 20×30 см',
    slug: 'tablichka-na-mogilu-z-kvitami-i-svichkami-20x30',
    price: 380,
    oldPrice: 450,
    sku: 'RIT-FLOWER-2030',
    status: 'В наявності',
    categoryId: 'cat-4',
    description: 'Ритуальна металева табличка з дизайном квітів та свічок. Індивідуальний УФ-друк.',
    image: 'https://images.prom.ua/6954006395_w500_h500_tablichka-na-mogilu.jpg',
    images: JSON.stringify(['https://images.prom.ua/6954006395_w500_h500_tablichka-na-mogilu.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2836970037',
    name: 'Магніт 14 ОМБр ім. князя Романа Великого 40×30 см | Емблема 14 бригади',
    slug: 'magnit-14-ombr-knyazya-romana-velikogo-40x30',
    price: 400,
    oldPrice: 480,
    sku: '14-OMBR-4030',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Офіційна магнітна емблема 14 Окремої Механізованої Бригади ім. князя Романа Великого.',
    image: 'https://images.prom.ua/6954084733_w500_h500_magnit-14-ombr.jpg',
    images: JSON.stringify(['https://images.prom.ua/6954084733_w500_h500_magnit-14-ombr.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2845132705',
    name: 'Магніт на авто з логотипом компанії | Рекламні магніти під замовлення',
    slug: 'magnit-na-avto-z-logotipom-kompaniyi',
    price: 400,
    oldPrice: 480,
    sku: 'LOGO-MAG-CUSTOM',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Виготовлення брендованих магнітів на авто з вашим логотипом та контактами.',
    image: 'https://images.prom.ua/6963133774_w500_h500_magnit-na-avto.jpg',
    images: JSON.stringify(['https://images.prom.ua/6963133774_w500_h500_magnit-na-avto.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2846303429',
    name: 'Магнітний знак «ЗАБОРОНЕНО ЗБРОЮ» 🚫🔫',
    slug: 'magnitnij-znak-zaboroneno-zbroyu',
    price: 400,
    oldPrice: 460,
    sku: 'NO-WEAPON-MAG',
    status: 'В наявності',
    categoryId: 'cat-3',
    description: 'Попереджувальний магнітний знак про заборону входу зі зброєю.',
    image: 'https://images.prom.ua/6964869484_w500_h500_magnitnij-znak-zaboreno.jpg',
    images: JSON.stringify(['https://images.prom.ua/6964869484_w500_h500_magnitnij-znak-zaboreno.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2846547733',
    name: 'Магніт для авто мисливської служби | Емблема мисливського господарства',
    slug: 'magnit-dlya-avto-mislirom-sluzhbi',
    price: 400,
    oldPrice: 480,
    sku: 'HUNT-SLUZHBA',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Спеціальний магнітний щит для авто мисливських та лісових служб.',
    image: 'https://images.prom.ua/6964943202_w500_h500_magnit-dlya-avto.jpg',
    images: JSON.stringify(['https://images.prom.ua/6964943202_w500_h500_magnit-dlya-avto.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2858651154',
    name: 'Інформаційний магніт з фото та ПІБ | Для авто та металу 40х30см',
    slug: 'informatsijnij-magnit-z-foto-ta-pib-40x30',
    price: 400,
    oldPrice: 480,
    sku: 'INFO-PHOTO-4030',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Персоналізований вініловий магніт з фотографією та текстовими даними.',
    image: 'https://images.prom.ua/6984629684_w500_h500_informatsijnij-magnit-z.jpg',
    images: JSON.stringify(['https://images.prom.ua/6984629684_w500_h500_informatsijnij-magnit-z.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2726219688',
    name: 'Авто номер з логотипом, назвою, іменний пластиковий',
    slug: 'avto-nomer-z-logotipom-nazvoyu-imennyj',
    price: 450,
    oldPrice: 520,
    sku: 'NUM-PLAST-CUSTOM',
    status: 'В наявності',
    categoryId: 'cat-5',
    description: 'Сувенірний автономер з пластику 4 мм з вашим індивідуальним дизайном.',
    image: 'https://images.prom.ua/6798246254_w500_h500_avto-nomer-z.jpg',
    images: JSON.stringify(['https://images.prom.ua/6798246254_w500_h500_avto-nomer-z.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2762127866',
    name: 'Табличка з логотипом з пластику 60*40см',
    slug: 'tablichka-z-logotipom-z-plastiku-60x40',
    price: 450,
    oldPrice: 520,
    sku: 'TAB-LOGO-6040',
    status: 'В наявності',
    categoryId: 'cat-4',
    description: 'Велика фасадна рекламну табличка з пластику ПВХ 4 мм розміром 60х40 см.',
    image: 'https://images.prom.ua/6840349114_w500_h500_tablichka-z-logotipom.jpg',
    images: JSON.stringify(['https://images.prom.ua/6840349114_w500_h500_tablichka-z-logotipom.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2796674894',
    name: 'Магнітна наліпка Едельвейс — 10 ОГШБр ЗСУ 40х30см',
    slug: 'magnitna-nalipka-edelvejs-10-ogshbr-40x30',
    price: 450,
    oldPrice: 520,
    sku: 'EDELWEISS-10',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітна наліпка 10-ї окремої гірсько-штурмової бригади "Едельвейс" 40х30 см.',
    image: 'https://images.prom.ua/6890869087_w500_h500_magnitna-nalipka-edelvejs.jpg',
    images: JSON.stringify(['https://images.prom.ua/6890869087_w500_h500_magnitna-nalipka-edelvejs.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2796676380',
    name: 'Магнітна наліпка Поліцейський офіцер громади — Чорнобаївська ТГ 40х30см',
    slug: 'magnitna-nalipka-politsejskij-ofitser-gromadi-40x30',
    price: 450,
    oldPrice: 520,
    sku: 'POLICE-COMM-4030',
    status: 'В наявності',
    categoryId: 'cat-3',
    description: 'Службова магнітна наліпка для патрульного транспорту Поліцейського офіцера громади.',
    image: 'https://images.prom.ua/6890873240_w500_h500_magnitna-nalipka-politsejskij.jpg',
    images: JSON.stringify(['https://images.prom.ua/6890873240_w500_h500_magnitna-nalipka-politsejskij.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2717470472',
    name: 'Наклейка магнітна на авто На Щиті 60*30см',
    slug: 'naklejka-magnitna-na-avto-na-shhiti-60x30',
    price: 500,
    oldPrice: 580,
    sku: 'SHHIT-6030',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Велика магнітна наклейка на авто "НА ЩИТІ" 60х30 см для евакуаційного транспорту.',
    image: 'https://images.prom.ua/6794390889_w500_h500_naklejka-magnitna-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6794390889_w500_h500_naklejka-magnitna-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2764037953',
    name: 'Наклейка магнітна на капот Хартія 50*40см',
    slug: 'naklejka-magnitna-na-kapot-hartiya-50x40',
    price: 500,
    oldPrice: 580,
    sku: 'HARTIYA-5040',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Великий капотний магніт бригади "Хартія" розміром 50х40 см.',
    image: 'https://images.prom.ua/6843553277_w500_h500_naklejka-magnitna-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6843553277_w500_h500_naklejka-magnitna-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2837347028',
    name: 'Магніти для бізнесу на авто — Рекламні магнітні таблички 60×30 см',
    slug: 'magnity-dlya-biznesu-na-avto-60x30',
    price: 500,
    oldPrice: 600,
    sku: 'BIZ-6030',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Великі рекламні магніти 60х30 см для нанесення логотипу, товарів та контактів вашого бізнесу.',
    image: 'https://images.prom.ua/6954747499_w500_h500_magniti-dlya-biznesu.jpg',
    images: JSON.stringify(['https://images.prom.ua/6954747499_w500_h500_magniti-dlya-biznesu.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2851334362',
    name: '«Ритуальний Транспорт» — магнітні знаки для ритуальних служб',
    slug: 'ritualnij-transport-dlya-sluzhb',
    price: 500,
    oldPrice: 580,
    sku: 'RIT-TRANS-01',
    status: 'В наявності',
    categoryId: 'cat-3',
    description: 'Чорні магнітні знаки з золотим нанесенням "Ритуальний Транспорт" на двері та капот.',
    image: 'https://images.prom.ua/6972607068_w500_h500_ritualnij-transport-.jpg',
    images: JSON.stringify(['https://images.prom.ua/6972607068_w500_h500_ritualnij-transport-.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2857836519',
    name: 'Магнітна наліпка на авто для енергетичних компаній 60×30 см (Обленерго / UDG)',
    slug: 'magnitna-nalipka-dlya-energetichnih-kompanij-60x30',
    price: 500,
    oldPrice: 600,
    sku: 'ENERGY-6030',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Службові магнітні наліпки для автомобілів аварійних бригад енергетиків.',
    image: 'https://images.prom.ua/6983189622_w500_h500_magnitna-nalipka-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6983189622_w500_h500_magnitna-nalipka-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2796668202',
    name: 'Магнітна наліпка «2-й механізований батальйон — мінометна батарея» 50х40см',
    slug: 'magnitna-nalipka-2j-mehanizovanij-bataljon-50x40',
    price: 550,
    oldPrice: 620,
    sku: '2BAT-5040',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Магнітна символіка 2-го механізованого батальйону мінометної батареї ЗСУ.',
    image: 'https://images.prom.ua/6890840474_w500_h500_magnitna-nalipka-2-j.jpg',
    images: JSON.stringify(['https://images.prom.ua/6890840474_w500_h500_magnitna-nalipka-2-j.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2836951719',
    name: 'Магнітна наліпка «ТРАКИ — СИЛА» 50×40 см Танкістський патріотичний магніт',
    slug: 'magnitna-nalipka-traki-sila-50x40',
    price: 550,
    oldPrice: 650,
    sku: 'TRAKI-5040',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Великий танкістський патріотичний магніт "ТРАКИ - СИЛА" 50х40 см.',
    image: 'https://images.prom.ua/6954050666_w500_h500_magnitna-nalipka-traki.jpg',
    images: JSON.stringify(['https://images.prom.ua/6954050666_w500_h500_magnitna-nalipka-traki.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2836985679',
    name: 'Магніт МБГ «NOSTRUM CAELUM» 50×50 см | Полювання на шахеди | Магніт ППО',
    slug: 'magnit-mbg-nostrum-caelum-50x50-ppo',
    price: 550,
    oldPrice: 650,
    sku: 'PPO-5050',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Спеціальний посилений магніт МБГ NOSTRUM CAELUM для підрозділів ППО та мобільних груп.',
    image: 'https://images.prom.ua/6954099113_w500_h500_magnit-mbg-nostrum.jpg',
    images: JSON.stringify(['https://images.prom.ua/6954099113_w500_h500_magnit-mbg-nostrum.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2845808098',
    name: 'Магніт “Тривога • Одеса” | Магнітні наліпки для моніторингових каналів',
    slug: 'magnit-trivoga-odesa-telegram',
    price: 550,
    oldPrice: 650,
    sku: 'TG-ODESA-550',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Рекламний магніт на авто моніторингового каналу "Тривога • Одеса".',
    image: 'https://images.prom.ua/6964121222_w500_h500_magnit-trivoga-.jpg',
    images: JSON.stringify(['https://images.prom.ua/6964121222_w500_h500_magnit-trivoga-.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2851269169',
    name: 'Магнітні наклепки DTEK на авто — брендування транспорту компаній',
    slug: 'magnitni-naklejki-dtek-na-avto',
    price: 550,
    oldPrice: 650,
    sku: 'DTEK-MAG-6030',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Магнітні наклейки ДТЕК для брендування спецтранспорту ремонтних бригад.',
    image: 'https://images.prom.ua/6971732736_w500_h500_magnitni-naklejki-dtek.jpg',
    images: JSON.stringify(['https://images.prom.ua/6971732736_w500_h500_magnitni-naklejki-dtek.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2853119421',
    name: 'Магнітний логотип “Нова Пошта” для авто',
    slug: 'magnitnij-logotip-nova-poshta-dlya-avto',
    price: 550,
    oldPrice: 650,
    sku: 'NP-LOGO-MAG',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Службовий магнітний знак "Нова Пошта" для кур’єрських автомобілів.',
    image: 'https://images.prom.ua/6974951075_w500_h500_magnitnij-logotip-nova.jpg',
    images: JSON.stringify(['https://images.prom.ua/6974951075_w500_h500_magnitnij-logotip-nova.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2853064385',
    name: 'Магнітна реклама на авто під ключ — Для бізнесу та послуг',
    slug: 'magnitna-reklama-na-avto-pid-klyuch',
    price: 600,
    oldPrice: 700,
    sku: 'REKLAMA-KEYS',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Повне виготовлення магнітної реклами на автомобіль з розробкою макету під ключ.',
    image: 'https://images.prom.ua/6974785195_w500_h500_magnitna-reklama-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6974785195_w500_h500_magnitna-reklama-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2853090489',
    name: 'Магнітний плакат на авто • Пошук водіїв • Індивідуальний дизайн',
    slug: 'magnitnij-plakat-na-avto-poshuk-vodiiv',
    price: 600,
    oldPrice: 700,
    sku: 'POSTER-DRIVERS',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Магнітний плакат для набору водіїв та курьєрів транспортними компаніями.',
    image: 'https://images.prom.ua/6974886132_w500_h500_magnitnij-plakat-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6974886132_w500_h500_magnitnij-plakat-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2856011175',
    name: 'Магнітна наліпка OPFOR | 214 ОШБ | Великий магніт на авто 60×50 см',
    slug: 'magnitna-nalipka-opfor-214-oshb-60x50',
    price: 650,
    oldPrice: 750,
    sku: 'OPFOR-6050',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Надвеликий капотний магніт 214-го окремого штурмового батальйону OPFOR 60х50 см.',
    image: 'https://images.prom.ua/6980282229_w500_h500_magnitna-nalipka-opfor.jpg',
    images: JSON.stringify(['https://images.prom.ua/6980282229_w500_h500_magnitna-nalipka-opfor.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2857852404',
    name: 'Магнітна рекламна наліпка Зоомагазин 90×30 см',
    slug: 'magnitna-reklamna-nalipka-zoomagazin-90x30',
    price: 700,
    oldPrice: 820,
    sku: 'ZOO-9030',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Довга магнітна смуга 90х30 см для автомобільних бортів та доставкових бусів.',
    image: 'https://images.prom.ua/6983225487_w500_h500_magnitna-reklamna-nalipka.jpg',
    images: JSON.stringify(['https://images.prom.ua/6983225487_w500_h500_magnitna-reklamna-nalipka.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2836960977',
    name: 'Меморіальна магнітна наліпка «НА ЩИТІ» Пам’ять про полеглих захисників',
    slug: 'memorialna-magnitna-nalipka-na-shhiti-750',
    price: 750,
    oldPrice: 850,
    sku: 'SHHIT-MEM-750',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Велика меморіальна магнітна наліпка "НА ЩИТІ" з високою атмосферостійкістю.',
    image: 'https://images.prom.ua/6954070793_w500_h500_memorialna-magnitna-nalipka.jpg',
    images: JSON.stringify(['https://images.prom.ua/6954070793_w500_h500_memorialna-magnitna-nalipka.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2854897984',
    name: 'Магніт на авто Тризуб Щит — великий патріотичний магніт 50×40 см',
    slug: 'magnit-na-avto-trizub-shhit-50x40',
    price: 750,
    oldPrice: 880,
    sku: 'TRZ-SHHIT-5040',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Велика капотна наліпка Щит з Тризубом 50х40 см. Посилена ламінація.',
    image: 'https://images.prom.ua/6978459258_w500_h500_magnit-na-avto.jpg',
    images: JSON.stringify(['https://images.prom.ua/6978459258_w500_h500_magnit-na-avto.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2857789941',
    name: 'Магнітна табличка на авто з вашим номером телефону — UV друк 70×60см',
    slug: 'magnitnaya-tablichka-avto-nomer-telefonu-70x60',
    price: 750,
    oldPrice: 850,
    sku: 'PHONE-MAG-7060',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Величезний магніт на авто з яскравим написом вашого номеру телефону та послуги.',
    image: 'https://images.prom.ua/6983114532_w500_h500_magnitna-tablichka-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6983114532_w500_h500_magnitna-tablichka-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2841374533',
    name: 'Магніт УТМР «Мисливство та риболовля» 70×60 см',
    slug: 'magnit-utmr-mislivstvo-ta-ribolovlya-70x60',
    price: 800,
    oldPrice: 920,
    sku: 'UTMR-7060',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Магніт великого розміру 70х60 см УТМР для мисливських позашляховиків.',
    image: 'https://images.prom.ua/6959084613_w500_h500_magnit-utmr-mislivstvo.jpg',
    images: JSON.stringify(['https://images.prom.ua/6959084613_w500_h500_magnit-utmr-mislivstvo.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2851294484',
    name: 'Магніти для авто “НОВА ПОШТА” (Комплект)',
    slug: 'magnity-dlya-avto-nova-poshta-komplekt',
    price: 900,
    oldPrice: 1050,
    sku: 'NP-SET-900',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Комплект з 2-х великих магнітів "Нова Пошта" для кур’єрського авто.',
    image: 'https://images.prom.ua/6971783155_w500_h500_magniti-dlya-avto.jpg',
    images: JSON.stringify(['https://images.prom.ua/6971783155_w500_h500_magniti-dlya-avto.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2851779635',
    name: 'Рекламний магніт на авто «Прочистка каналізації» + дизайн під ключ',
    slug: 'reklamnij-magnit-avto-prochishtka-kanalizatsiyi',
    price: 900,
    oldPrice: 1050,
    sku: 'PLUMB-MAG-900',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Повноформатна автомобільна реклама сантехнічних послуг та прочистки каналізації.',
    image: 'https://images.prom.ua/6972622591_w500_h500_reklamnij-magnit-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6972622591_w500_h500_reklamnij-magnit-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2838772850',
    name: 'Комплект магнітів «Я не з ТЦК» Патріотичний гумор (3 в 1)',
    slug: 'komplekt-magnitov-ya-ne-z-tczk-3in1',
    price: 1000,
    oldPrice: 1200,
    sku: 'TCK-SET-3IN1',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Комплект магнітних наліпок (капот + кабіна + борт) "Я не з ТЦК".',
    image: 'https://images.prom.ua/6955692096_w500_h500_komplekt-magnitiv-ya.jpg',
    images: JSON.stringify(['https://images.prom.ua/6955692096_w500_h500_komplekt-magnitiv-ya.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2841186767',
    name: 'Магнітний рекламний банер на авто з вашим дизайном',
    slug: 'magnitnij-reklamnij-baner-na-avto-custom',
    price: 1000,
    oldPrice: 1200,
    sku: 'BANNER-MAG-1000',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Надвеликий рекламний магнітний банер на автотранспорт за вашим макетом.',
    image: 'https://images.prom.ua/6964175201_w500_h500_magnitnij-reklamnij-baner.jpg',
    images: JSON.stringify(['https://images.prom.ua/6964175201_w500_h500_magnitnij-reklamnij-baner.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2841266346',
    name: 'Магнітна реклама на авто KUMIKUM (Комплект для автопарку)',
    slug: 'magnitna-reklama-avto-kumikum',
    price: 1400,
    oldPrice: 1600,
    sku: 'KUMIKUM-SET',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Комплект магнітного брендування для комерційного автотранспорту.',
    image: 'https://images.prom.ua/6958962284_w500_h500_magnitna-reklama-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6958962284_w500_h500_magnitna-reklama-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
  {
    id: 'p2854804511',
    name: 'Комплект магнітів на авто «НА ЩИТІ» — капотний + бокові (3-в-1)',
    slug: 'komplekt-magnitov-avto-na-shhite-3in1',
    price: 1600,
    oldPrice: 1900,
    sku: 'SHHIT-3IN1-FULL',
    status: 'В наявності',
    categoryId: 'cat-2',
    description: 'Повний професійний комплект магнітних знаків "НА ЩИТІ" 3-в-1 для автомобілів.',
    image: 'https://images.prom.ua/6978358217_w500_h500_komplekt-magnitiv-na.jpg',
    images: JSON.stringify(['https://images.prom.ua/6978358217_w500_h500_komplekt-magnitiv-na.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: true,
  },
  {
    id: 'p2851302310',
    name: 'Магнітна наклейка Umbrella Corporation Resident Evil',
    slug: 'magnitnaya-naklejka-umbrella-resident-evil',
    price: 400,
    oldPrice: 480,
    sku: 'UMBRELLA-RES',
    status: 'В наявності',
    categoryId: 'cat-1',
    description: 'Магнітний символ Umbrella Corporation з серії Resident Evil на авто та двері.',
    image: 'https://images.prom.ua/6971786509_w500_h500_magnitna-naklejka-umbrella.jpg',
    images: JSON.stringify(['https://images.prom.ua/6971786509_w500_h500_magnitna-naklejka-umbrella.jpg']),
    unit: 'шт.',
    features: '[]',
    isFeatured: false,
  },
];
