import { Product, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Магнітні наліпки на авто',
    slug: 'magnitni-nalipki-na-avto',
    image: 'https://images.prom.ua/4296986097_w297_h200_magnitni-nalipki-na.jpg',
    description: 'Міцні вінілові магніти на авто із захисною ламінацією від непогоди та УФ.',
    isFeatured: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    "id": "p2851787526",
    "name": "Магнітні візитки для майстрів: сантехнік | електрик | опалення | ремонт",
    "slug": "магнітні-візитки-для-майстрів-сантехнік-електрик-о-7526",
    "price": 20,
    "oldPrice": 24,
    "sku": "SKU-7526",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітні візитки для майстрів: сантехнік | електрик | опалення | ремонт",
    "image": "https://images.prom.ua/6972629971_w500_h500_magnitni-vizitki-dlya.jpg",
    "images": "[\"https://images.prom.ua/6972629971_w500_h500_magnitni-vizitki-dlya.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2845969109",
    "name": "Магнітний рекламний постер — Вугілля / Дрова / Брикети",
    "slug": "магнітний-рекламний-постер-вугілля-дрова-брикети-9109",
    "price": 100,
    "oldPrice": 118,
    "sku": "SKU-9109",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний рекламний постер — Вугілля / Дрова / Брикети",
    "image": "https://images.prom.ua/6964220216_w500_h500_magnitnij-reklamnij-poster.jpg",
    "images": "[\"https://images.prom.ua/6964220216_w500_h500_magnitnij-reklamnij-poster.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2846338378",
    "name": "Магніти для Служб Охорони",
    "slug": "магніти-для-служб-охорони-8378",
    "price": 100,
    "oldPrice": 118,
    "sku": "SKU-8378",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніти для Служб Охорони",
    "image": "https://images.prom.ua/6964688153_w500_h500_magniti-dlya-sluzhb.jpg",
    "images": "[\"https://images.prom.ua/6964688153_w500_h500_magniti-dlya-sluzhb.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2846576177",
    "name": "Смішний магніт на авто “ГороПчик, а шо ти робиш?” | Український гумор мем",
    "slug": "смішний-магніт-на-авто-горопчик-а-шо-ти-робиш-укра-6177",
    "price": 100,
    "oldPrice": 118,
    "sku": "SKU-6177",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Смішний магніт на авто “ГороПчик, а шо ти робиш?” | Український гумор мем",
    "image": "https://images.prom.ua/6971735141_w500_h500_smishnij-magnit-na.jpg",
    "images": "[\"https://images.prom.ua/6971735141_w500_h500_smishnij-magnit-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2853083971",
    "name": "Патріотичний магніт на авто Тризуб | Магнітні наклейки ЗСУ | Сотні варіантів герба України | Доставка по Україні",
    "slug": "патріотичний-магніт-на-авто-тризуб-магнітні-наклей-3971",
    "price": 100,
    "oldPrice": 118,
    "sku": "SKU-3971",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Патріотичний магніт на авто Тризуб | Магнітні наклейки ЗСУ | Сотні варіантів герба України | Доставка по Україні",
    "image": "https://images.prom.ua/6974843980_w500_h500_patriotichnij-magnit-na.jpg",
    "images": "[\"https://images.prom.ua/6974843980_w500_h500_patriotichnij-magnit-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2717952132",
    "name": "Наклейка ЗСУ квадрат сине жовтий 30*30см",
    "slug": "наклейка-зсу-квадрат-сине-жовтий-30-30см-2132",
    "price": 125,
    "oldPrice": 148,
    "sku": "квадрат",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка ЗСУ квадрат сине жовтий 30*30см",
    "image": "https://images.prom.ua/6794611879_w500_h500_naklejka-zsu-kvadrat.jpg",
    "images": "[\"https://images.prom.ua/6794611879_w500_h500_naklejka-zsu-kvadrat.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2735821997",
    "name": "Наклейка магнітна на авто Колона 15*15см",
    "slug": "наклейка-магнітна-на-авто-колона-15-15см-1997",
    "price": 130,
    "oldPrice": 153,
    "sku": "колона",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна на авто Колона 15*15см",
    "image": "https://images.prom.ua/6809609685_w500_h500_naklejka-magnitna-na.jpg",
    "images": "[\"https://images.prom.ua/6809609685_w500_h500_naklejka-magnitna-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2716395430",
    "name": "Наклейка магнітна Каблук 15*15см",
    "slug": "наклейка-магнітна-каблук-15-15см-5430",
    "price": 150,
    "oldPrice": 177,
    "sku": "каблук",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна Каблук 15*15см",
    "image": "https://images.prom.ua/6793705342_w500_h500_naklejka-magnitna-kabluk.jpg",
    "images": "[\"https://images.prom.ua/6793705342_w500_h500_naklejka-magnitna-kabluk.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2716465738",
    "name": "Наклейка квадрат ЗСУ стрілка 40*40см",
    "slug": "наклейка-квадрат-зсу-стрілка-40-40см-5738",
    "price": 150,
    "oldPrice": 177,
    "sku": "наклейка",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка квадрат ЗСУ стрілка 40*40см",
    "image": "https://images.prom.ua/6793762684_w500_h500_naklejka-kvadrat-zsu.jpg",
    "images": "[\"https://images.prom.ua/6793762684_w500_h500_naklejka-kvadrat-zsu.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2717729965",
    "name": "Наклейка магнітна Вовки Да Вінчі 15*15см",
    "slug": "наклейка-магнітна-вовки-да-вінчі-15-15см-9965",
    "price": 150,
    "oldPrice": 177,
    "sku": "да вінчі",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна Вовки Да Вінчі 15*15см",
    "image": "https://images.prom.ua/6794528403_w500_h500_naklejka-magnitna-vovki.jpg",
    "images": "[\"https://images.prom.ua/6794528403_w500_h500_naklejka-magnitna-vovki.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2739844214",
    "name": "Наклейка магнітна на авто",
    "slug": "наклейка-магнітна-на-авто-4214",
    "price": 150,
    "oldPrice": 177,
    "sku": "20*20см",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна на авто",
    "image": "https://images.prom.ua/6959027759_w500_h500_naklejka-magnitna-na.jpg",
    "images": "[\"https://images.prom.ua/6959027759_w500_h500_naklejka-magnitna-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2845101710",
    "name": "Магніт на авто Герб Микуличин | Магнітний герб міста | Виготовлення гербів міст під замовлення",
    "slug": "магніт-на-авто-герб-микуличин-магнітний-герб-міста-1710",
    "price": 150,
    "oldPrice": 177,
    "sku": "SKU-1710",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто Герб Микуличин | Магнітний герб міста | Виготовлення гербів міст під замовлення",
    "image": "https://images.prom.ua/6963042275_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6963042275_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2718682424",
    "name": "Табличка з пластику Паркування заборонено 30*20см",
    "slug": "табличка-з-пластику-паркування-заборонено-30-20см-2424",
    "price": 180,
    "oldPrice": 212,
    "sku": "паркування",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Табличка з пластику Паркування заборонено 30*20см",
    "image": "https://images.prom.ua/6795155337_w500_h500_tablichka-z-plastiku.jpg",
    "images": "[\"https://images.prom.ua/6795155337_w500_h500_tablichka-z-plastiku.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2843193642",
    "name": "Магніт на авто Єгерська служба | Щит з гербом України | Мисливці, УТМР 20х15см",
    "slug": "магніт-на-авто-єгерська-служба-щит-з-гербом-україн-3642",
    "price": 180,
    "oldPrice": 212,
    "sku": "ег",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто Єгерська служба | Щит з гербом України | Мисливці, УТМР 20х15см",
    "image": "https://images.prom.ua/6960970817_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6960970817_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2713534620",
    "name": "Сувенірні автономера з позивним",
    "slug": "сувенірні-автономера-з-позивним-4620",
    "price": 200,
    "oldPrice": 236,
    "sku": "позивний",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Сувенірні автономера з позивним",
    "image": "https://images.prom.ua/6960951508_w500_h500_suvenirni-avtonomera-z.jpg",
    "images": "[\"https://images.prom.ua/6960951508_w500_h500_suvenirni-avtonomera-z.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2717507021",
    "name": "Транзитні автономера пластикові",
    "slug": "транзитні-автономера-пластикові-7021",
    "price": 200,
    "oldPrice": 236,
    "sku": "транзитні ",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Транзитні автономера пластикові",
    "image": "https://images.prom.ua/6794393214_w500_h500_tranzitni-avtonomera-plastikovi.jpg",
    "images": "[\"https://images.prom.ua/6794393214_w500_h500_tranzitni-avtonomera-plastikovi.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2762673304",
    "name": "Магнітна наклейка на авто 1 ОШП «Да Вінчі» 25*20см",
    "slug": "магнітна-наклейка-на-авто-1-ошп-да-вінчі-25-20см-3304",
    "price": 200,
    "oldPrice": 236,
    "sku": "1ошп",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наклейка на авто 1 ОШП «Да Вінчі» 25*20см",
    "image": "https://images.prom.ua/6841302692_w500_h500_magnitna-naklejka-na.jpg",
    "images": "[\"https://images.prom.ua/6841302692_w500_h500_magnitna-naklejka-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2764392664",
    "name": "Волонтер магнітна наліпка на авто",
    "slug": "волонтер-магнітна-наліпка-на-авто-2664",
    "price": 200,
    "oldPrice": 236,
    "sku": "волонтер",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Волонтер магнітна наліпка на авто",
    "image": "https://images.prom.ua/6844236685_w500_h500_volonter-magnitna-nalipka.jpg",
    "images": "[\"https://images.prom.ua/6844236685_w500_h500_volonter-magnitna-nalipka.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2784266269",
    "name": "Сувенірний номер EUROCAR  CARZONE — 519×112 мм  УФ-друк | Пластик Алюмінієвий композит",
    "slug": "сувенірний-номер-eurocar-carzone-519-112-мм-уф-дру-6269",
    "price": 200,
    "oldPrice": 236,
    "sku": "SKU-6269",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Сувенірний номер EUROCAR  CARZONE — 519×112 мм  УФ-друк | Пластик Алюмінієвий композит",
    "image": "https://images.prom.ua/6871345002_w500_h500_suvenirnij-nomer-eurocar.jpg",
    "images": "[\"https://images.prom.ua/6871345002_w500_h500_suvenirnij-nomer-eurocar.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2785004530",
    "name": "Сувенірний номер  (ДШВ ЗСУ) | 519×112 мм Пластик Алюмінієвий композит",
    "slug": "сувенірний-номер-дшв-зсу-519-112-мм-пластик-алюмін-4530",
    "price": 200,
    "oldPrice": 236,
    "sku": "SKU-4530",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Сувенірний номер  (ДШВ ЗСУ) | 519×112 мм Пластик Алюмінієвий композит",
    "image": "https://images.prom.ua/6872756468_w500_h500_suvenirnij-nomer-dshv.jpg",
    "images": "[\"https://images.prom.ua/6872756468_w500_h500_suvenirnij-nomer-dshv.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2858010933",
    "name": "Сувенірний номер на авто «МЕХАНІК» | УФ друк, пластик стандартний розмір 52×11 см | Патріотична табличка на машину",
    "slug": "сувенірний-номер-на-авто-механік-уф-друк-пластик-с-0933",
    "price": 200,
    "oldPrice": 236,
    "sku": "SKU-0933",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Сувенірний номер на авто «МЕХАНІК» | УФ друк, пластик стандартний розмір 52×11 см | Патріотична табличка на машину",
    "image": "https://images.prom.ua/6983588355_w500_h500_suvenirnij-nomer-na.jpg",
    "images": "[\"https://images.prom.ua/6983588355_w500_h500_suvenirnij-nomer-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2858591923",
    "name": "Сувенірні авто номери на алюмінієвому композиті | Для військових, автошкіл, оренди авто, позивних | УФ друк пластик",
    "slug": "сувенірні-авто-номери-на-алюмінієвому-композиті-дл-1923",
    "price": 200,
    "oldPrice": 236,
    "sku": "SKU-1923",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Сувенірні авто номери на алюмінієвому композиті | Для військових, автошкіл, оренди авто, позивних | УФ друк пластик",
    "image": "https://images.prom.ua/6984586040_w500_h500_suvenirni-avto-nomeri.jpg",
    "images": "[\"https://images.prom.ua/6984586040_w500_h500_suvenirni-avto-nomeri.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2764161335",
    "name": "Магнітна наклейка на авто ЗСУ 25*25см",
    "slug": "магнітна-наклейка-на-авто-зсу-25-25см-1335",
    "price": 220,
    "oldPrice": 260,
    "sku": "ЗСУ 25",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наклейка на авто ЗСУ 25*25см",
    "image": "https://images.prom.ua/6843747891_w500_h500_magnitna-naklejka-na.jpg",
    "images": "[\"https://images.prom.ua/6843747891_w500_h500_magnitna-naklejka-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2735613139",
    "name": "Авто номер військовий з алюмінію композиту",
    "slug": "авто-номер-військовий-з-алюмінію-композиту-3139",
    "price": 230,
    "oldPrice": 271,
    "sku": "композит",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Авто номер військовий з алюмінію композиту",
    "image": "https://images.prom.ua/6809283765_w500_h500_avto-nomer-vijskovij.jpg",
    "images": "[\"https://images.prom.ua/6809283765_w500_h500_avto-nomer-vijskovij.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2854299656",
    "name": "Світловідбиваючий магніт на авто “К” | Reflective Edition Попереджувальний знак | УФ-друк | 15×15 см",
    "slug": "світловідбиваючий-магніт-на-авто-к-reflective-edit-9656",
    "price": 230,
    "oldPrice": 271,
    "sku": "SKU-9656",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Світловідбиваючий магніт на авто “К” | Reflective Edition Попереджувальний знак | УФ-друк | 15×15 см",
    "image": "https://images.prom.ua/6976967220_w500_h500_svitlovidbivayuchij-magnit-na.jpg",
    "images": "[\"https://images.prom.ua/6976967220_w500_h500_svitlovidbivayuchij-magnit-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2767106194",
    "name": "Холодний яр 93 бригада магнітна наклейка на авто 30*25см",
    "slug": "холодний-яр-93-бригада-магнітна-наклейка-на-авто-3-6194",
    "price": 240,
    "oldPrice": 283,
    "sku": "93 омбр",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Холодний яр 93 бригада магнітна наклейка на авто 30*25см",
    "image": "https://images.prom.ua/6848857086_w500_h500_holodnij-yar-93.jpg",
    "images": "[\"https://images.prom.ua/6848857086_w500_h500_holodnij-yar-93.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2716279483",
    "name": "Магнітна наклейка Морська піхота 25*25см",
    "slug": "магнітна-наклейка-морська-піхота-25-25см-9483",
    "price": 250,
    "oldPrice": 295,
    "sku": "морська піхота",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наклейка Морська піхота 25*25см",
    "image": "https://images.prom.ua/6793582624_w500_h500_magnitna-naklejka-morska.jpg",
    "images": "[\"https://images.prom.ua/6793582624_w500_h500_magnitna-naklejka-morska.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2718235525",
    "name": "Наклейка магнітна на авто не тцк",
    "slug": "наклейка-магнітна-на-авто-не-тцк-5525",
    "price": 250,
    "oldPrice": 295,
    "sku": "стандарт магніт",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна на авто не тцк",
    "image": "https://images.prom.ua/6794796469_w500_h500_naklejka-magnitna-na.jpg",
    "images": "[\"https://images.prom.ua/6794796469_w500_h500_naklejka-magnitna-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2718330310",
    "name": "Наклейка магнітна на авто Чеченський Батальйон імені Шейха Мансури",
    "slug": "наклейка-магнітна-на-авто-чеченський-батальйон-іме-0310",
    "price": 250,
    "oldPrice": 295,
    "sku": "чеченський батальйон",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна на авто Чеченський Батальйон імені Шейха Мансури",
    "image": "https://images.prom.ua/6794832854_w500_h500_naklejka-magnitna-na.jpg",
    "images": "[\"https://images.prom.ua/6794832854_w500_h500_naklejka-magnitna-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2735605646",
    "name": "Наклейка магнітна на авто Герб",
    "slug": "наклейка-магнітна-на-авто-герб-5646",
    "price": 250,
    "oldPrice": 295,
    "sku": "Герб 30*25см",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна на авто Герб",
    "image": "https://images.prom.ua/6809275833_w500_h500_naklejka-magnitna-na.jpg",
    "images": "[\"https://images.prom.ua/6809275833_w500_h500_naklejka-magnitna-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2736888342",
    "name": "Наклейка магнітна на авто 214 ошб Опфор",
    "slug": "наклейка-магнітна-на-авто-214-ошб-опфор-8342",
    "price": 250,
    "oldPrice": 295,
    "sku": "214 ошб 30*20см",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна на авто 214 ошб Опфор",
    "image": "https://images.prom.ua/6811237861_w500_h500_naklejka-magnitna-na.jpg",
    "images": "[\"https://images.prom.ua/6811237861_w500_h500_naklejka-magnitna-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2763120359",
    "name": "Магнітна наклейка на авто з назвою Міста 15*50см",
    "slug": "магнітна-наклейка-на-авто-з-назвою-міста-15-50см-0359",
    "price": 250,
    "oldPrice": 295,
    "sku": "місто 15*50см",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наклейка на авто з назвою Міста 15*50см",
    "image": "https://images.prom.ua/6842099578_w500_h500_magnitna-naklejka-na.jpg",
    "images": "[\"https://images.prom.ua/6842099578_w500_h500_magnitna-naklejka-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2767863447",
    "name": "Магнітна наклейка на авто Волонтер 20*50см",
    "slug": "магнітна-наклейка-на-авто-волонтер-20-50см-3447",
    "price": 250,
    "oldPrice": 295,
    "sku": "20*50",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наклейка на авто Волонтер 20*50см",
    "image": "https://images.prom.ua/6850199197_w500_h500_magnitna-naklejka-na.jpg",
    "images": "[\"https://images.prom.ua/6850199197_w500_h500_magnitna-naklejka-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2784998410",
    "name": "Сувенірний номер  з логотипом TikTok  519×112 мм Пластик Алюмінієвий композит на авто",
    "slug": "сувенірний-номер-з-логотипом-tiktok-519-112-мм-пла-8410",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-8410",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Сувенірний номер  з логотипом TikTok  519×112 мм Пластик Алюмінієвий композит на авто",
    "image": "https://images.prom.ua/6872750324_w500_h500_suvenirnij-nomer-z.jpg",
    "images": "[\"https://images.prom.ua/6872750324_w500_h500_suvenirnij-nomer-z.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2785005575",
    "name": "Сувенірний номер з позивним ДШВ ЗСУ 519×112 мм | Пластик  Алюмінієвий композит",
    "slug": "сувенірний-номер-з-позивним-дшв-зсу-519-112-мм-пла-5575",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-5575",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Сувенірний номер з позивним ДШВ ЗСУ 519×112 мм | Пластик  Алюмінієвий композит",
    "image": "https://images.prom.ua/6872759938_w500_h500_suvenirnij-nomer-z.jpg",
    "images": "[\"https://images.prom.ua/6872759938_w500_h500_suvenirnij-nomer-z.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2845932307",
    "name": "Магніт на авто «Охорона мисливського фонду» | МРК «Дружба»",
    "slug": "магніт-на-авто-охорона-мисливського-фонду-мрк-друж-2307",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-2307",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто «Охорона мисливського фонду» | МРК «Дружба»",
    "image": "https://images.prom.ua/6964189924_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6964189924_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2846253851",
    "name": "СУВЕНІРНІ АВТОНОМЕРИ УФ-друк | Пластик ПВХ 4 мм | Алюмінієвий композит",
    "slug": "сувенірні-автономери-уф-друк-пластик-пвх-4-мм-алюм-3851",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-3851",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "СУВЕНІРНІ АВТОНОМЕРИ УФ-друк | Пластик ПВХ 4 мм | Алюмінієвий композит",
    "image": "https://images.prom.ua/6964512384_w500_h500_suvenirni-avtonomeri-uf-druk.jpg",
    "images": "[\"https://images.prom.ua/6964512384_w500_h500_suvenirni-avtonomeri-uf-druk.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2851307059",
    "name": "Магніт “НАВЧАЛЬНИЙ” на авто | Ученик за рулем | Знак Учбовий автомобіль, знімний магніт",
    "slug": "магніт-навчальний-на-авто-ученик-за-рулем-знак-учб-7059",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-7059",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт “НАВЧАЛЬНИЙ” на авто | Ученик за рулем | Знак Учбовий автомобіль, знімний магніт",
    "image": "https://images.prom.ua/6971790306_w500_h500_magnit-navchalnij-na.jpg",
    "images": "[\"https://images.prom.ua/6971790306_w500_h500_magnit-navchalnij-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2851333308",
    "name": "Магніт на авто НКБК | Національний комітет по боротьбі з корупцією 🚔 Щит меч Тризуб | Патріотичний автомагніт",
    "slug": "магніт-на-авто-нкбк-національний-комітет-по-бороть-3308",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-3308",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто НКБК | Національний комітет по боротьбі з корупцією 🚔 Щит меч Тризуб | Патріотичний автомагніт",
    "image": "https://images.prom.ua/6971867404_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6971867404_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2851816163",
    "name": "Магніт / Наліпка для авто “Риболовля у Лиса” | Подарунок рибалці | Реклама форелевих ставків",
    "slug": "магніт-наліпка-для-авто-риболовля-у-лиса-подарунок-6163",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-6163",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт / Наліпка для авто “Риболовля у Лиса” | Подарунок рибалці | Реклама форелевих ставків",
    "image": "https://images.prom.ua/6972688910_w500_h500_magnit--nalipka.jpg",
    "images": "[\"https://images.prom.ua/6972688910_w500_h500_magnit--nalipka.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2853137920",
    "name": "УФ-друк на пластику – таблички, шеврони, емблеми під ваш підрозділ",
    "slug": "уф-друк-на-пластику-таблички-шеврони-емблеми-під-в-7920",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-7920",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "УФ-друк на пластику – таблички, шеврони, емблеми під ваш підрозділ",
    "image": "https://images.prom.ua/6974979331_w500_h500_uf-druk-na-plastiku.jpg",
    "images": "[\"https://images.prom.ua/6974979331_w500_h500_uf-druk-na-plastiku.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2853141514",
    "name": "Шеврон 39 Окрема Бригада – УФ друк на пластику | Настінна табличка для підрозділу",
    "slug": "шеврон-39-окрема-бригада-уф-друк-на-пластику-насті-1514",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-1514",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Шеврон 39 Окрема Бригада – УФ друк на пластику | Настінна табличка для підрозділу",
    "image": "https://images.prom.ua/6974993061_w500_h500_shevron-39-okrema.jpg",
    "images": "[\"https://images.prom.ua/6974993061_w500_h500_shevron-39-okrema.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2854299476",
    "name": "Магніт на авто  | Патріотичний гумор | Прикольний магніт | УФ-друк | 50х12 см",
    "slug": "магніт-на-авто-патріотичний-гумор-прикольний-магні-9476",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-9476",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто  | Патріотичний гумор | Прикольний магніт | УФ-друк | 50х12 см",
    "image": "https://images.prom.ua/6976962824_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6976962824_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2856003177",
    "name": "Сувенірний номер 52×12 см • Ультрафіолетовий друк • Алюмінієвий композит",
    "slug": "сувенірний-номер-52-12-см-ультрафіолетовий-друк-ал-3177",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-3177",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Сувенірний номер 52×12 см • Ультрафіолетовий друк • Алюмінієвий композит",
    "image": "https://images.prom.ua/6980266248_w500_h500_suvenirnij-nomer-5212.jpg",
    "images": "[\"https://images.prom.ua/6980266248_w500_h500_suvenirnij-nomer-5212.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2858585428",
    "name": "Іменні сувенірні авто номери | Металеві таблички | Композит, ультрафіолетовий друк",
    "slug": "іменні-сувенірні-авто-номери-металеві-таблички-ком-5428",
    "price": 250,
    "oldPrice": 295,
    "sku": "SKU-5428",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Іменні сувенірні авто номери | Металеві таблички | Композит, ультрафіолетовий друк",
    "image": "https://images.prom.ua/6984560673_w500_h500_imenni-suvenirni-avto.jpg",
    "images": "[\"https://images.prom.ua/6984560673_w500_h500_imenni-suvenirni-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2855610493",
    "name": "Магнітний розпізнавальний знак ЗСУ «Стрілки» нова пошта 30х30см  для авто",
    "slug": "магнітний-розпізнавальний-знак-зсу-стрілки-нова-по-0493",
    "price": 260,
    "oldPrice": 307,
    "sku": "SKU-0493",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний розпізнавальний знак ЗСУ «Стрілки» нова пошта 30х30см  для авто",
    "image": "https://images.prom.ua/6979540477_w500_h500_magnitnij-rozpiznavalnij-znak.jpg",
    "images": "[\"https://images.prom.ua/6979540477_w500_h500_magnitnij-rozpiznavalnij-znak.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2855621359",
    "name": "Магнітний розпізнавальний знак КРУГ 30х30см на авто | Білий / Чорний / Оливковий",
    "slug": "магнітний-розпізнавальний-знак-круг-30х30см-на-авт-1359",
    "price": 260,
    "oldPrice": 307,
    "sku": "SKU-1359",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний розпізнавальний знак КРУГ 30х30см на авто | Білий / Чорний / Оливковий",
    "image": "https://images.prom.ua/6979546265_w500_h500_magnitnij-rozpiznavalnij-znak.jpg",
    "images": "[\"https://images.prom.ua/6979546265_w500_h500_magnitnij-rozpiznavalnij-znak.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2855717564",
    "name": "Магнітний розпізнавальний знак “Три стрілки” 30х30 см | Білий / Чорний / Оливковий",
    "slug": "магнітний-розпізнавальний-знак-три-стрілки-30х30-с-7564",
    "price": 260,
    "oldPrice": 307,
    "sku": "SKU-7564",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний розпізнавальний знак “Три стрілки” 30х30 см | Білий / Чорний / Оливковий",
    "image": "https://images.prom.ua/6979724586_w500_h500_magnitnij-rozpiznavalnij-znak.jpg",
    "images": "[\"https://images.prom.ua/6979724586_w500_h500_magnitnij-rozpiznavalnij-znak.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2855721505",
    "name": "Магнітний розпізнавальний знак “Дві стрілки” 30х30 см | Чорний / Білий / Оливковий",
    "slug": "магнітний-розпізнавальний-знак-дві-стрілки-30х30-с-1505",
    "price": 260,
    "oldPrice": 307,
    "sku": "SKU-1505",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний розпізнавальний знак “Дві стрілки” 30х30 см | Чорний / Білий / Оливковий",
    "image": "https://images.prom.ua/6979730435_w500_h500_magnitnij-rozpiznavalnij-znak.jpg",
    "images": "[\"https://images.prom.ua/6979730435_w500_h500_magnitnij-rozpiznavalnij-znak.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2857819029",
    "name": "Розпізнавальний знак ЗСУ «Синій квадрат з жовтим центром» — магнітна наліпка для авто, броні, техніки 30х30см",
    "slug": "розпізнавальний-знак-зсу-синій-квадрат-з-жовтим-це-9029",
    "price": 270,
    "oldPrice": 319,
    "sku": "SKU-9029",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Розпізнавальний знак ЗСУ «Синій квадрат з жовтим центром» — магнітна наліпка для авто, броні, техніки 30х30см",
    "image": "https://images.prom.ua/6983166722_w500_h500_rozpiznavalnij-znak-zsu.jpg",
    "images": "[\"https://images.prom.ua/6983166722_w500_h500_rozpiznavalnij-znak-zsu.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2836849539",
    "name": "Табличка на могилу з ПІБ та датами Металева ритуальна табличка Виготовлення під замовлення",
    "slug": "табличка-на-могилу-з-піб-та-датами-металева-ритуал-9539",
    "price": 290,
    "oldPrice": 342,
    "sku": "SKU-9539",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Табличка на могилу з ПІБ та датами Металева ритуальна табличка Виготовлення під замовлення",
    "image": "https://images.prom.ua/6953913321_w500_h500_tablichka-na-mogilu.jpg",
    "images": "[\"https://images.prom.ua/6953913321_w500_h500_tablichka-na-mogilu.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2841495496",
    "name": "Новорічні магніти на авто та холодильник | Святковий декор 2025 🎄",
    "slug": "новорічні-магніти-на-авто-та-холодильник-святковий-5496",
    "price": 300,
    "oldPrice": 354,
    "sku": "Н\\Г",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Новорічні магніти на авто та холодильник | Святковий декор 2025 🎄",
    "image": "https://images.prom.ua/6959200222_w500_h500_novorichni-magniti-na.jpg",
    "images": "[\"https://images.prom.ua/6959200222_w500_h500_novorichni-magniti-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2845906340",
    "name": "Магніт на авто RADAR Rivne | Моніторинговий канал | Патріотичний магніт",
    "slug": "магніт-на-авто-radar-rivne-моніторинговий-канал-па-6340",
    "price": 300,
    "oldPrice": 354,
    "sku": "SKU-6340",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто RADAR Rivne | Моніторинговий канал | Патріотичний магніт",
    "image": "https://images.prom.ua/6964172662_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6964172662_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2846080191",
    "name": "Магнітний попереджувальний знак  “НЕБЕЗПЕЧНО МІНИ! / DANGER MINES!”",
    "slug": "магнітний-попереджувальний-знак-небезпечно-міни-da-0191",
    "price": 300,
    "oldPrice": 354,
    "sku": "SKU-0191",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний попереджувальний знак  “НЕБЕЗПЕЧНО МІНИ! / DANGER MINES!”",
    "image": "https://images.prom.ua/6964342845_w500_h500_magnitnij-poperedzhuvalnij-znak.jpg",
    "images": "[\"https://images.prom.ua/6964342845_w500_h500_magnitnij-poperedzhuvalnij-znak.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2853128875",
    "name": "Магніт «Хрест ЗСУ»",
    "slug": "магніт-хрест-зсу-8875",
    "price": 300,
    "oldPrice": 354,
    "sku": "SKU-8875",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт «Хрест ЗСУ»",
    "image": "https://images.prom.ua/6974968945_w500_h500_magnit-hrest-zsu.jpg",
    "images": "[\"https://images.prom.ua/6974968945_w500_h500_magnit-hrest-zsu.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2855401139",
    "name": "Магнітний розпізнавальний на капот ромб 30×30 см з жовтим центром та синьою окантовкою — магніт на авто",
    "slug": "магнітний-розпізнавальний-на-капот-ромб-30-30-см-з-1139",
    "price": 300,
    "oldPrice": 354,
    "sku": "SKU-1139",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний розпізнавальний на капот ромб 30×30 см з жовтим центром та синьою окантовкою — магніт на авто",
    "image": "https://images.prom.ua/6979401473_w500_h500_magnitnij-rozpiznavalnij-na.jpg",
    "images": "[\"https://images.prom.ua/6979401473_w500_h500_magnitnij-rozpiznavalnij-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2716301832",
    "name": "Наклейка магнітна 3су квадрат чорний 40*40см",
    "slug": "наклейка-магнітна-3су-квадрат-чорний-40-40см-1832",
    "price": 350,
    "oldPrice": 413,
    "sku": "квадрат",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна 3су квадрат чорний 40*40см",
    "image": "https://images.prom.ua/6793599433_w500_h500_naklejka-magnitna-3su.jpg",
    "images": "[\"https://images.prom.ua/6793599433_w500_h500_naklejka-magnitna-3su.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2731079224",
    "name": "Наклейка магнітна На Щиті",
    "slug": "наклейка-магнітна-на-щиті-9224",
    "price": 350,
    "oldPrice": 413,
    "sku": "на щиті",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна На Щиті",
    "image": "https://images.prom.ua/6802740870_w500_h500_naklejka-magnitna-na.jpg",
    "images": "[\"https://images.prom.ua/6802740870_w500_h500_naklejka-magnitna-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2764155441",
    "name": "Магнітна наклейка на авто Народна варта 40*35см",
    "slug": "магнітна-наклейка-на-авто-народна-варта-40-35см-5441",
    "price": 350,
    "oldPrice": 413,
    "sku": "народна варта",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наклейка на авто Народна варта 40*35см",
    "image": "https://images.prom.ua/6843738795_w500_h500_magnitna-naklejka-na.jpg",
    "images": "[\"https://images.prom.ua/6843738795_w500_h500_magnitna-naklejka-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2784169432",
    "name": "Магніт на авто «През шаблі маєм право» 40×30 см | Історичний герб | Патріотичний магніт",
    "slug": "магніт-на-авто-през-шаблі-маєм-право-40-30-см-істо-9432",
    "price": 350,
    "oldPrice": 413,
    "sku": "SKU-9432",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто «През шаблі маєм право» 40×30 см | Історичний герб | Патріотичний магніт",
    "image": "https://images.prom.ua/6871162471_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6871162471_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2784185322",
    "name": "Магніт на капот 1 ОШБ «Вовк» 40×30 см | Символ штурмовиків | Патріотичний магніт",
    "slug": "магніт-на-капот-1-ошб-вовк-40-30-см-символ-штурмов-5322",
    "price": 350,
    "oldPrice": 413,
    "sku": "SKU-5322",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на капот 1 ОШБ «Вовк» 40×30 см | Символ штурмовиків | Патріотичний магніт",
    "image": "https://images.prom.ua/6871193113_w500_h500_magnit-na-kapot.jpg",
    "images": "[\"https://images.prom.ua/6871193113_w500_h500_magnit-na-kapot.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2784194189",
    "name": "Магніт «Народна Варта» 40×30 см  Символ захисту  Патріотичний магніт",
    "slug": "магніт-народна-варта-40-30-см-символ-захисту-патрі-4189",
    "price": 350,
    "oldPrice": 413,
    "sku": "SKU-4189",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт «Народна Варта» 40×30 см  Символ захисту  Патріотичний магніт",
    "image": "https://images.prom.ua/6871209409_w500_h500_magnit-narodna-varta.jpg",
    "images": "[\"https://images.prom.ua/6871209409_w500_h500_magnit-narodna-varta.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2784212576",
    "name": "Магніт Морська піхота ЗСУ «Вірний завжди» 40×30 см | Офіційна емблема | Магніт на авто",
    "slug": "магніт-морська-піхота-зсу-вірний-завжди-40-30-см-о-2576",
    "price": 350,
    "oldPrice": 413,
    "sku": "SKU-2576",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт Морська піхота ЗСУ «Вірний завжди» 40×30 см | Офіційна емблема | Магніт на авто",
    "image": "https://images.prom.ua/6871227674_w500_h500_magnit-morska-pihota.jpg",
    "images": "[\"https://images.prom.ua/6871227674_w500_h500_magnit-morska-pihota.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2784223065",
    "name": "Магніт «Холодний Яр» 40×30 см | Історичний символ | Патріотичний магніт України",
    "slug": "магніт-холодний-яр-40-30-см-історичний-символ-патр-3065",
    "price": 350,
    "oldPrice": 413,
    "sku": "SKU-3065",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт «Холодний Яр» 40×30 см | Історичний символ | Патріотичний магніт України",
    "image": "https://images.prom.ua/6871245461_w500_h500_magnit-holodnij-yar.jpg",
    "images": "[\"https://images.prom.ua/6871245461_w500_h500_magnit-holodnij-yar.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2784237923",
    "name": "Магніт «Серце і меч» 40×30 см Символ воїна  Патріотичний сувенір 39 бригада",
    "slug": "магніт-серце-і-меч-40-30-см-символ-воїна-патріотич-7923",
    "price": 350,
    "oldPrice": 413,
    "sku": "SKU-7923",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт «Серце і меч» 40×30 см Символ воїна  Патріотичний сувенір 39 бригада",
    "image": "https://images.prom.ua/6871305523_w500_h500_magnit-sertse-i.jpg",
    "images": "[\"https://images.prom.ua/6871305523_w500_h500_magnit-sertse-i.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2796682515",
    "name": "Магніт Добровольчий батальйон УЦМ 40×30 см | Символ підрозділу | Магніт на авто",
    "slug": "магніт-добровольчий-батальйон-уцм-40-30-см-символ--2515",
    "price": 350,
    "oldPrice": 413,
    "sku": "уцм 40*30",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт Добровольчий батальйон УЦМ 40×30 см | Символ підрозділу | Магніт на авто",
    "image": "https://images.prom.ua/6960906056_w500_h500_magnit-dobrovolchij-bataljon.jpg",
    "images": "[\"https://images.prom.ua/6960906056_w500_h500_magnit-dobrovolchij-bataljon.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2838747503",
    "name": "Магнітна наклейка на капот «Й…аний цирк» | Патріотичний гумор | Магніт 30×20 / 40×30 / 50×40 см",
    "slug": "магнітна-наклейка-на-капот-й-аний-цирк-патріотични-7503",
    "price": 350,
    "oldPrice": 413,
    "sku": "SKU-7503",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наклейка на капот «Й…аний цирк» | Патріотичний гумор | Магніт 30×20 / 40×30 / 50×40 см",
    "image": "https://images.prom.ua/6955671160_w500_h500_magnitna-naklejka-na.jpg",
    "images": "[\"https://images.prom.ua/6955671160_w500_h500_magnitna-naklejka-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2838777330",
    "name": "Рекламний магніт для бізнесу «Пивна Бухта №1»  Магніт-табличка на авто/холодильник  Реклама магазину",
    "slug": "рекламний-магніт-для-бізнесу-пивна-бухта-1-магніт--7330",
    "price": 350,
    "oldPrice": 413,
    "sku": "SKU-7330",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Рекламний магніт для бізнесу «Пивна Бухта №1»  Магніт-табличка на авто/холодильник  Реклама магазину",
    "image": "https://images.prom.ua/6955704240_w500_h500_reklamnij-magnit-dlya.jpg",
    "images": "[\"https://images.prom.ua/6955704240_w500_h500_reklamnij-magnit-dlya.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2846513929",
    "name": "Магніт на ворота “Паркування заборонено” | Попереджувальна табличка No Parking",
    "slug": "магніт-на-ворота-паркування-заборонено-попереджува-3929",
    "price": 350,
    "oldPrice": 413,
    "sku": "SKU-3929",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на ворота “Паркування заборонено” | Попереджувальна табличка No Parking",
    "image": "https://images.prom.ua/6964922718_w500_h500_magnit-na-vorota.jpg",
    "images": "[\"https://images.prom.ua/6964922718_w500_h500_magnit-na-vorota.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2851776483",
    "name": "Магніт на авто “Не бійся! Я не з ТЦК” | Військовий шеврон на машину ЗСУ | Велика магнітна наклейка на авто",
    "slug": "магніт-на-авто-не-бійся-я-не-з-тцк-військовий-шевр-6483",
    "price": 350,
    "oldPrice": 413,
    "sku": "SKU-6483",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто “Не бійся! Я не з ТЦК” | Військовий шеврон на машину ЗСУ | Велика магнітна наклейка на авто",
    "image": "https://images.prom.ua/6972615205_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6972615205_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2796670243",
    "name": "Магнітна наліпка Воїн з бородою — череп у шоломі магніти на авто авто магніти",
    "slug": "магнітна-наліпка-воїн-з-бородою-череп-у-шоломі-маг-0243",
    "price": 360,
    "oldPrice": 425,
    "sku": "SKU-0243",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наліпка Воїн з бородою — череп у шоломі магніти на авто авто магніти",
    "image": "https://images.prom.ua/6890852146_w500_h500_magnitna-nalipka-voyin.jpg",
    "images": "[\"https://images.prom.ua/6890852146_w500_h500_magnitna-nalipka-voyin.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2836921956",
    "name": "Табличка на могилу з квітами і свічками  Металева пам’ятна табличка 20×30 см",
    "slug": "табличка-на-могилу-з-квітами-і-свічками-металева-п-1956",
    "price": 380,
    "oldPrice": 448,
    "sku": "SKU-1956",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Табличка на могилу з квітами і свічками  Металева пам’ятна табличка 20×30 см",
    "image": "https://images.prom.ua/6954006395_w500_h500_tablichka-na-mogilu.jpg",
    "images": "[\"https://images.prom.ua/6954006395_w500_h500_tablichka-na-mogilu.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2836970037",
    "name": "Магніт 14 ОМБр ім. князя Романа Великого 40×30 см | Патріотичний магніт на авто | Емблема 14 бригади",
    "slug": "магніт-14-омбр-ім-князя-романа-великого-40-30-см-п-0037",
    "price": 400,
    "oldPrice": 472,
    "sku": "SKU-0037",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт 14 ОМБр ім. князя Романа Великого 40×30 см | Патріотичний магніт на авто | Емблема 14 бригади",
    "image": "https://images.prom.ua/6954084733_w500_h500_magnit-14-ombr.jpg",
    "images": "[\"https://images.prom.ua/6954084733_w500_h500_magnit-14-ombr.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2845132705",
    "name": "Магніт на авто з логотипом компанії | Рекламні магніти під замовлення",
    "slug": "магніт-на-авто-з-логотипом-компанії-рекламні-магні-2705",
    "price": 400,
    "oldPrice": 472,
    "sku": "SKU-2705",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто з логотипом компанії | Рекламні магніти під замовлення",
    "image": "https://images.prom.ua/6963133774_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6963133774_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2846303429",
    "name": "Магнітний знак «ЗАБОРОНЕНО ЗБРОЮ» 🚫🔫",
    "slug": "магнітний-знак-заборонено-зброю-3429",
    "price": 400,
    "oldPrice": 472,
    "sku": "SKU-3429",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний знак «ЗАБОРОНЕНО ЗБРОЮ» 🚫🔫",
    "image": "https://images.prom.ua/6964869484_w500_h500_magnitnij-znak-zaboroneno.jpg",
    "images": "[\"https://images.prom.ua/6964869484_w500_h500_magnitnij-znak-zaboroneno.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2846547733",
    "name": "Магніт для авто мисливської служби | Індивідуальний друк емблем мисливського господарства",
    "slug": "магніт-для-авто-мисливської-служби-індивідуальний--7733",
    "price": 400,
    "oldPrice": 472,
    "sku": "SKU-7733",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт для авто мисливської служби | Індивідуальний друк емблем мисливського господарства",
    "image": "https://images.prom.ua/6964943202_w500_h500_magnit-dlya-avto.jpg",
    "images": "[\"https://images.prom.ua/6964943202_w500_h500_magnit-dlya-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2858651154",
    "name": "Інформаційний магніт з фото та ПІБ | Для розміщення на авто та металі 40х30см",
    "slug": "інформаційний-магніт-з-фото-та-піб-для-розміщення--1154",
    "price": 400,
    "oldPrice": 472,
    "sku": "SKU-1154",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Інформаційний магніт з фото та ПІБ | Для розміщення на авто та металі 40х30см",
    "image": "https://images.prom.ua/6984629684_w500_h500_informatsijnij-magnit-z.jpg",
    "images": "[\"https://images.prom.ua/6984629684_w500_h500_informatsijnij-magnit-z.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2726219688",
    "name": "Авто номер з логотипом, назвою, іменний",
    "slug": "авто-номер-з-логотипом-назвою-іменний-9688",
    "price": 450,
    "oldPrice": 531,
    "sku": "пластик",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Авто номер з логотипом, назвою, іменний",
    "image": "https://images.prom.ua/6798246254_w500_h500_avto-nomer-z.jpg",
    "images": "[\"https://images.prom.ua/6798246254_w500_h500_avto-nomer-z.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2762127866",
    "name": "Табличка з логотипом з пластику 60*40см",
    "slug": "табличка-з-логотипом-з-пластику-60-40см-7866",
    "price": 450,
    "oldPrice": 531,
    "sku": "таб 60*40",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Табличка з логотипом з пластику 60*40см",
    "image": "https://images.prom.ua/6840349114_w500_h500_tablichka-z-logotipom.jpg",
    "images": "[\"https://images.prom.ua/6840349114_w500_h500_tablichka-z-logotipom.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2796674894",
    "name": "Магнітна наліпка Едельвейс — 10 ОГШБр ЗСУ 40х30см",
    "slug": "магнітна-наліпка-едельвейс-10-огшбр-зсу-40х30см-4894",
    "price": 450,
    "oldPrice": 531,
    "sku": "SKU-4894",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наліпка Едельвейс — 10 ОГШБр ЗСУ 40х30см",
    "image": "https://images.prom.ua/6890869087_w500_h500_magnitna-nalipka-edelvejs.jpg",
    "images": "[\"https://images.prom.ua/6890869087_w500_h500_magnitna-nalipka-edelvejs.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2796676380",
    "name": "Магнітна наліпка Поліцейський офіцер громади — Чорнобаївська ТГ 40х30см",
    "slug": "магнітна-наліпка-поліцейський-офіцер-громади-чорно-6380",
    "price": 450,
    "oldPrice": 531,
    "sku": "SKU-6380",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наліпка Поліцейський офіцер громади — Чорнобаївська ТГ 40х30см",
    "image": "https://images.prom.ua/6890873240_w500_h500_magnitna-nalipka-politsejskij.jpg",
    "images": "[\"https://images.prom.ua/6890873240_w500_h500_magnitna-nalipka-politsejskij.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2717470472",
    "name": "Наклейка магнітна на авто На Щиті 60*30см",
    "slug": "наклейка-магнітна-на-авто-на-щиті-60-30см-0472",
    "price": 500,
    "oldPrice": 590,
    "sku": "60*30см",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна на авто На Щиті 60*30см",
    "image": "https://images.prom.ua/6794390889_w500_h500_naklejka-magnitna-na.jpg",
    "images": "[\"https://images.prom.ua/6794390889_w500_h500_naklejka-magnitna-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2764037953",
    "name": "Наклейка магнітна на капот Хартія 50*40см",
    "slug": "наклейка-магнітна-на-капот-хартія-50-40см-7953",
    "price": 500,
    "oldPrice": 590,
    "sku": "50*40",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Наклейка магнітна на капот Хартія 50*40см",
    "image": "https://images.prom.ua/6843553277_w500_h500_naklejka-magnitna-na.jpg",
    "images": "[\"https://images.prom.ua/6843553277_w500_h500_naklejka-magnitna-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2837347028",
    "name": "Магніти для бізнесу на авто  Рекламні магнітні таблички під замовлення 60×30 см індивідуально",
    "slug": "магніти-для-бізнесу-на-авто-рекламні-магнітні-табл-7028",
    "price": 500,
    "oldPrice": 590,
    "sku": "для бізнесу",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніти для бізнесу на авто  Рекламні магнітні таблички під замовлення 60×30 см індивідуально",
    "image": "https://images.prom.ua/6954747499_w500_h500_magniti-dlya-biznesu.jpg",
    "images": "[\"https://images.prom.ua/6954747499_w500_h500_magniti-dlya-biznesu.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2846504042",
    "name": "Магніт на авто з рекламою | Магнітна реклама на автомобіль | Під замовлення — Україна",
    "slug": "магніт-на-авто-з-рекламою-магнітна-реклама-на-авто-4042",
    "price": 500,
    "oldPrice": 590,
    "sku": "SKU-4042",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто з рекламою | Магнітна реклама на автомобіль | Під замовлення — Україна",
    "image": "https://images.prom.ua/6964912499_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6964912499_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2851334362",
    "name": "«Ритуальний Транспорт» — для ритуальних служб | Чорний з золотом",
    "slug": "ритуальний-транспорт-для-ритуальних-служб-чорний-з-4362",
    "price": 500,
    "oldPrice": 590,
    "sku": "SKU-4362",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "«Ритуальний Транспорт» — для ритуальних служб | Чорний з золотом",
    "image": "https://images.prom.ua/6972607068_w500_h500_ritualnij-transport-.jpg",
    "images": "[\"https://images.prom.ua/6972607068_w500_h500_ritualnij-transport-.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2853105615",
    "name": "Магніт на авто «На щиті – Слава Герою!»",
    "slug": "магніт-на-авто-на-щиті-слава-герою-5615",
    "price": 500,
    "oldPrice": 590,
    "sku": "SKU-5615",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто «На щиті – Слава Герою!»",
    "image": "https://images.prom.ua/6974914334_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6974914334_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2857836519",
    "name": "Магнітна наліпка на авто для енергетичних компаній 60×30 см | Службова табличка Черкаси Обленерго / UDG / Енергетики",
    "slug": "магнітна-наліпка-на-авто-для-енергетичних-компаній-6519",
    "price": 500,
    "oldPrice": 590,
    "sku": "SKU-6519",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наліпка на авто для енергетичних компаній 60×30 см | Службова табличка Черкаси Обленерго / UDG / Енергетики",
    "image": "https://images.prom.ua/6983189622_w500_h500_magnitna-nalipka-na.jpg",
    "images": "[\"https://images.prom.ua/6983189622_w500_h500_magnitna-nalipka-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2796668202",
    "name": "Магнітна наліпка «2-й механізований батальйон — мінометна батарея» 50х40см  Захисна символіка ЗСУ  Магніт",
    "slug": "магнітна-наліпка-2-й-механізований-батальйон-міном-8202",
    "price": 550,
    "oldPrice": 649,
    "sku": "SKU-8202",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наліпка «2-й механізований батальйон — мінометна батарея» 50х40см  Захисна символіка ЗСУ  Магніт",
    "image": "https://images.prom.ua/6890840474_w500_h500_magnitna-nalipka-2-j.jpg",
    "images": "[\"https://images.prom.ua/6890840474_w500_h500_magnitna-nalipka-2-j.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2836951719",
    "name": "Магнітна наліпка «ТРАКИ — СИЛА» 50×40 см Танкістський патріотичний магніт  Символіка ЗСУ",
    "slug": "магнітна-наліпка-траки-сила-50-40-см-танкістський--1719",
    "price": 550,
    "oldPrice": 649,
    "sku": "SKU-1719",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наліпка «ТРАКИ — СИЛА» 50×40 см Танкістський патріотичний магніт  Символіка ЗСУ",
    "image": "https://images.prom.ua/6954050666_w500_h500_magnitna-nalipka-traki.jpg",
    "images": "[\"https://images.prom.ua/6954050666_w500_h500_magnitna-nalipka-traki.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2836985679",
    "name": "Магніт МБГ «NOSTRUM CAELUM» 50×50 см | Полювання на шахеди | Магніт ППО на авто",
    "slug": "магніт-мбг-nostrum-caelum-50-50-см-полювання-на-ша-5679",
    "price": 550,
    "oldPrice": 649,
    "sku": "SKU-5679",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт МБГ «NOSTRUM CAELUM» 50×50 см | Полювання на шахеди | Магніт ППО на авто",
    "image": "https://images.prom.ua/6954099113_w500_h500_magnit-mbg-nostrum.jpg",
    "images": "[\"https://images.prom.ua/6954099113_w500_h500_magnit-mbg-nostrum.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2841357306",
    "name": "Рекламний магніт для авто — для бізнесу та доставки",
    "slug": "рекламний-магніт-для-авто-для-бізнесу-та-доставки-7306",
    "price": 550,
    "oldPrice": 649,
    "sku": "SKU-7306",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Рекламний магніт для авто — для бізнесу та доставки",
    "image": "https://images.prom.ua/6959044996_w500_h500_reklamnij-magnit-dlya.jpg",
    "images": "[\"https://images.prom.ua/6959044996_w500_h500_reklamnij-magnit-dlya.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2845808098",
    "name": "Магніт “Тривога • Одеса” | Магнітні наліпки для моніторингових каналів | Реклама Telegram-каналу",
    "slug": "магніт-тривога-одеса-магнітні-наліпки-для-монітори-8098",
    "price": 550,
    "oldPrice": 649,
    "sku": "SKU-8098",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт “Тривога • Одеса” | Магнітні наліпки для моніторингових каналів | Реклама Telegram-каналу",
    "image": "https://images.prom.ua/6964121222_w500_h500_magnit-trivoga-.jpg",
    "images": "[\"https://images.prom.ua/6964121222_w500_h500_magnit-trivoga-.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2851269169",
    "name": "Магнітні наклейки DTEK на авто — брендування транспорту для компаній та бригад",
    "slug": "магнітні-наклейки-dtek-на-авто-брендування-транспо-9169",
    "price": 550,
    "oldPrice": 649,
    "sku": "SKU-9169",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітні наклейки DTEK на авто — брендування транспорту для компаній та бригад",
    "image": "https://images.prom.ua/6971732736_w500_h500_magnitni-naklejki-dtek.jpg",
    "images": "[\"https://images.prom.ua/6971732736_w500_h500_magnitni-naklejki-dtek.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2853119421",
    "name": "Магнітний логотип “Нова Пошта” для авто",
    "slug": "магнітний-логотип-нова-пошта-для-авто-9421",
    "price": 550,
    "oldPrice": 649,
    "sku": "SKU-9421",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний логотип “Нова Пошта” для авто",
    "image": "https://images.prom.ua/6974951075_w500_h500_magnitnij-logotip-nova.jpg",
    "images": "[\"https://images.prom.ua/6974951075_w500_h500_magnitnij-logotip-nova.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2853064385",
    "name": "Магнітна реклама на авто | Виготовлення під ключ | Для бізнесу і послуг | Доставка по Україні",
    "slug": "магнітна-реклама-на-авто-виготовлення-під-ключ-для-4385",
    "price": 600,
    "oldPrice": 708,
    "sku": "SKU-4385",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна реклама на авто | Виготовлення під ключ | Для бізнесу і послуг | Доставка по Україні",
    "image": "https://images.prom.ua/6974785195_w500_h500_magnitna-reklama-na.jpg",
    "images": "[\"https://images.prom.ua/6974785195_w500_h500_magnitna-reklama-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2853090489",
    "name": "Магнітний плакат на авто • Пошук водіїв • Індивідуальний дизайн • Транспортні компанії",
    "slug": "магнітний-плакат-на-авто-пошук-водіїв-індивідуальн-0489",
    "price": 600,
    "oldPrice": 708,
    "sku": "SKU-0489",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний плакат на авто • Пошук водіїв • Індивідуальний дизайн • Транспортні компанії",
    "image": "https://images.prom.ua/6974886132_w500_h500_magnitnij-plakat-na.jpg",
    "images": "[\"https://images.prom.ua/6974886132_w500_h500_magnitnij-plakat-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2856011175",
    "name": "Магнітна наліпка OPFOR | 214 ОШБ | Великий магніт на авто 60×50 см",
    "slug": "магнітна-наліпка-opfor-214-ошб-великий-магніт-на-а-1175",
    "price": 650,
    "oldPrice": 767,
    "sku": "SKU-1175",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна наліпка OPFOR | 214 ОШБ | Великий магніт на авто 60×50 см",
    "image": "https://images.prom.ua/6980282229_w500_h500_magnitna-nalipka-opfor.jpg",
    "images": "[\"https://images.prom.ua/6980282229_w500_h500_magnitna-nalipka-opfor.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2857852404",
    "name": "Магнітна рекламна наліпка Зоомагазин | Магніт на авто та метал | Розмір 90х30 см",
    "slug": "магнітна-рекламна-наліпка-зоомагазин-магніт-на-авт-2404",
    "price": 700,
    "oldPrice": 826,
    "sku": "SKU-2404",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна рекламна наліпка Зоомагазин | Магніт на авто та метал | Розмір 90х30 см",
    "image": "https://images.prom.ua/6983225487_w500_h500_magnitna-reklamna-nalipka.jpg",
    "images": "[\"https://images.prom.ua/6983225487_w500_h500_magnitna-reklamna-nalipka.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2836960977",
    "name": "Меморіальна магнітна наліпка «НА ЩИТІ»  Пам’ять про полеглих захисників України",
    "slug": "меморіальна-магнітна-наліпка-на-щиті-пам-ять-про-п-0977",
    "price": 750,
    "oldPrice": 885,
    "sku": "SKU-0977",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Меморіальна магнітна наліпка «НА ЩИТІ»  Пам’ять про полеглих захисників України",
    "image": "https://images.prom.ua/6954070793_w500_h500_memorialna-magnitna-nalipka.jpg",
    "images": "[\"https://images.prom.ua/6954070793_w500_h500_memorialna-magnitna-nalipka.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2854897984",
    "name": "Магніт на авто Тризуб Щит — великий патріотичний магніт 50×40 см для капота та дверей",
    "slug": "магніт-на-авто-тризуб-щит-великий-патріотичний-маг-7984",
    "price": 750,
    "oldPrice": 885,
    "sku": "SKU-7984",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт на авто Тризуб Щит — великий патріотичний магніт 50×40 см для капота та дверей",
    "image": "https://images.prom.ua/6978459258_w500_h500_magnit-na-avto.jpg",
    "images": "[\"https://images.prom.ua/6978459258_w500_h500_magnit-na-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2857789941",
    "name": "Магнітна табличка на авто з вашим номером телефону — UV друк 70х60см",
    "slug": "магнітна-табличка-на-авто-з-вашим-номером-телефону-9941",
    "price": 750,
    "oldPrice": 885,
    "sku": "SKU-9941",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна табличка на авто з вашим номером телефону — UV друк 70х60см",
    "image": "https://images.prom.ua/6983114532_w500_h500_magnitna-tablichka-na.jpg",
    "images": "[\"https://images.prom.ua/6983114532_w500_h500_magnitna-tablichka-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2841374533",
    "name": "Магніт УТМР «Мисливство та риболовля» 70х60 см  Магнітна наліпка на авто",
    "slug": "магніт-утмр-мисливство-та-риболовля-70х60-см-магні-4533",
    "price": 800,
    "oldPrice": 944,
    "sku": "УТМР",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніт УТМР «Мисливство та риболовля» 70х60 см  Магнітна наліпка на авто",
    "image": "https://images.prom.ua/6959084613_w500_h500_magnit-utmr-mislivstvo.jpg",
    "images": "[\"https://images.prom.ua/6959084613_w500_h500_magnit-utmr-mislivstvo.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2851294484",
    "name": "Магніти для авто “НОВА ПОШТА”",
    "slug": "магніти-для-авто-нова-пошта-4484",
    "price": 900,
    "oldPrice": 1062,
    "sku": "SKU-4484",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магніти для авто “НОВА ПОШТА”",
    "image": "https://images.prom.ua/6971783155_w500_h500_magniti-dlya-avto.jpg",
    "images": "[\"https://images.prom.ua/6971783155_w500_h500_magniti-dlya-avto.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2851779635",
    "name": "Рекламний магніт на авто «Прочистка каналізації» + дизайн під ключ",
    "slug": "рекламний-магніт-на-авто-прочистка-каналізації-диз-9635",
    "price": 900,
    "oldPrice": 1062,
    "sku": "SKU-9635",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Рекламний магніт на авто «Прочистка каналізації» + дизайн під ключ",
    "image": "https://images.prom.ua/6972622591_w500_h500_reklamnij-magnit-na.jpg",
    "images": "[\"https://images.prom.ua/6972622591_w500_h500_reklamnij-magnit-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2838772850",
    "name": "Комплект магнітів «Я не з ТЦК»  Патріотичний гумор для військових  Магніти на авто",
    "slug": "комплект-магнітів-я-не-з-тцк-патріотичний-гумор-дл-2850",
    "price": 1000,
    "oldPrice": 1180,
    "sku": "SKU-2850",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Комплект магнітів «Я не з ТЦК»  Патріотичний гумор для військових  Магніти на авто",
    "image": "https://images.prom.ua/6955692096_w500_h500_komplekt-magnitiv-ya.jpg",
    "images": "[\"https://images.prom.ua/6955692096_w500_h500_komplekt-magnitiv-ya.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2841186767",
    "name": "Магнітний рекламний банер на авто стіни з вашим дизайном",
    "slug": "магнітний-рекламний-банер-на-авто-стіни-з-вашим-ди-6767",
    "price": 1000,
    "oldPrice": 1180,
    "sku": "SKU-6767",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітний рекламний банер на авто стіни з вашим дизайном",
    "image": "https://images.prom.ua/6964175201_w500_h500_magnitnij-reklamnij-baner.jpg",
    "images": "[\"https://images.prom.ua/6964175201_w500_h500_magnitnij-reklamnij-baner.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2841266346",
    "name": "Магнітна реклама на авто KUMIKUM",
    "slug": "магнітна-реклама-на-авто-kumikum-6346",
    "price": 1400,
    "oldPrice": 1652,
    "sku": "SKU-6346",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Магнітна реклама на авто KUMIKUM",
    "image": "https://images.prom.ua/6958962284_w500_h500_magnitna-reklama-na.jpg",
    "images": "[\"https://images.prom.ua/6958962284_w500_h500_magnitna-reklama-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2854804511",
    "name": "Комплект магнітів на авто «НА ЩИТІ» — великий капотний + бокові щитки | 3-в-1 автомобільний",
    "slug": "комплект-магнітів-на-авто-на-щиті-великий-капотний-4511",
    "price": 1600,
    "oldPrice": 1888,
    "sku": "SKU-4511",
    "status": "В наявності",
    "categoryId": "cat-1",
    "description": "Комплект магнітів на авто «НА ЩИТІ» — великий капотний + бокові щитки | 3-в-1 автомобільний",
    "image": "https://images.prom.ua/6978358217_w500_h500_komplekt-magnitiv-na.jpg",
    "images": "[\"https://images.prom.ua/6978358217_w500_h500_komplekt-magnitiv-na.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": true
  },
  {
    "id": "p2855571903",
    "name": "Магнітний хрест ЗСУ 15×15 см на авто | Білий або Чорний з окантуванням",
    "slug": "магнітний-хрест-зсу-15-15-см-на-авто-білий-або-чор-1903",
    "price": 98,
    "oldPrice": 116,
    "sku": "SKU-1903",
    "status": "Під замовлення",
    "categoryId": "cat-1",
    "description": "Магнітний хрест ЗСУ 15×15 см на авто | Білий або Чорний з окантуванням",
    "image": "https://images.prom.ua/6979516750_w500_h500_magnitnij-hrest-zsu.jpg",
    "images": "[\"https://images.prom.ua/6979516750_w500_h500_magnitnij-hrest-zsu.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  },
  {
    "id": "p2851302310",
    "name": "Магнітна наклейка Umbrella Corporation Resident Evil | Логотип біо корпорації на авто, капот, двері",
    "slug": "магнітна-наклейка-umbrella-corporation-resident-ev-2310",
    "price": 400,
    "oldPrice": 472,
    "sku": "SKU-2310",
    "status": "Під замовлення",
    "categoryId": "cat-1",
    "description": "Магнітна наклейка Umbrella Corporation Resident Evil | Логотип біо корпорації на авто, капот, двері",
    "image": "https://images.prom.ua/6971786509_w500_h500_magnitna-naklejka-umbrella.jpg",
    "images": "[\"https://images.prom.ua/6971786509_w500_h500_magnitna-naklejka-umbrella.jpg\"]",
    "unit": "шт.",
    "features": "[]",
    "isFeatured": false
  }
];
